package com.tgfc.som.mapper;

import com.tgfc.som.entity.Channel;
import com.tgfc.som.entity.ChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    long countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int insert(Channel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int insertSelective(Channel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    Channel selectByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Channel row, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Channel row, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Channel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Channel row);
}