package com.tgfc.som.mapper;

import com.tgfc.som.entity.Store;
import com.tgfc.som.entity.StoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    long countByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int deleteByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int insert(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int insertSelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    Store selectByPrimaryKey(String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Store row);
}