package com.tgfc.som.mapper;

import com.tgfc.som.entity.TblOrderCompute;
import com.tgfc.som.entity.TblOrderComputeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOrderComputeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    long countByExample(TblOrderComputeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    int deleteByExample(TblOrderComputeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    int insert(TblOrderCompute row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    int insertSelective(TblOrderCompute row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    List<TblOrderCompute> selectByExample(TblOrderComputeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TblOrderCompute row, @Param("example") TblOrderComputeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TblOrderCompute row, @Param("example") TblOrderComputeExample example);
}