package com.tgfc.som.mapper;

import com.tgfc.som.entity.TblOrderDetl;
import com.tgfc.som.entity.TblOrderDetlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOrderDetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    long countByExample(TblOrderDetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int deleteByExample(TblOrderDetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderId") String orderId, @Param("detlSeqId") String detlSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int insert(TblOrderDetl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int insertSelective(TblOrderDetl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    List<TblOrderDetl> selectByExample(TblOrderDetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    TblOrderDetl selectByPrimaryKey(@Param("orderId") String orderId, @Param("detlSeqId") String detlSeqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TblOrderDetl row, @Param("example") TblOrderDetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TblOrderDetl row, @Param("example") TblOrderDetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblOrderDetl row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_DETL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblOrderDetl row);
}