package com.tgfc.som.mapper;

import com.tgfc.som.entity.TblOrder;
import com.tgfc.som.entity.TblOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    long countByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int deleteByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int insert(TblOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int insertSelective(TblOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    List<TblOrder> selectByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    TblOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TblOrder row, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TblOrder row, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblOrder row);
}