package com.tgfc.som.mapper;

import com.tgfc.som.entity.TblSkuStore;
import com.tgfc.som.entity.TblSkuStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSkuStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    long countByExample(TblSkuStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int deleteByExample(TblSkuStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("storeId") String storeId, @Param("skuNo") String skuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int insert(TblSkuStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int insertSelective(TblSkuStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    List<TblSkuStore> selectByExample(TblSkuStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    TblSkuStore selectByPrimaryKey(@Param("storeId") String storeId, @Param("skuNo") String skuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TblSkuStore row, @Param("example") TblSkuStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TblSkuStore row, @Param("example") TblSkuStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblSkuStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblSkuStore row);
}