package com.tgfc.som.mapper;

import com.tgfc.som.entity.TblSku;
import com.tgfc.som.entity.TblSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    long countByExample(TblSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int deleteByExample(TblSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String skuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int insert(TblSku row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int insertSelective(TblSku row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    List<TblSku> selectByExample(TblSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    TblSku selectByPrimaryKey(String skuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TblSku row, @Param("example") TblSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TblSku row, @Param("example") TblSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblSku row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblSku row);
}