package com.tgfc.som.mapper;

import com.tgfc.som.entity.UserStore;
import com.tgfc.som.entity.UserStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    long countByExample(UserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int deleteByExample(UserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("empId") String empId, @Param("storeId") String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int insert(UserStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int insertSelective(UserStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    List<UserStore> selectByExample(UserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    UserStore selectByPrimaryKey(@Param("empId") String empId, @Param("storeId") String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserStore row, @Param("example") UserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserStore row, @Param("example") UserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserStore row);
}