package com.tgfc.som.mapper;

import com.tgfc.som.entity.UserMastStore;
import com.tgfc.som.entity.UserMastStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMastStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    long countByExample(UserMastStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    int deleteByExample(UserMastStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    int insert(UserMastStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    int insertSelective(UserMastStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    List<UserMastStore> selectByExample(UserMastStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserMastStore row, @Param("example") UserMastStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_MAST_STORE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserMastStore row, @Param("example") UserMastStoreExample example);
}