package com.tgfc.som.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   通路檔
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_CHANNEL
 */
public class Channel implements Serializable {
    /**
     * Database Column Remarks:
     *   通路別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.CHANNEL_ID
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   通路名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated
     */
    private String channelName;

    /**
     * Database Column Remarks:
     *   CRM下傳CHANNEL編號, 為紅利點數中CHANNEL關聯的欄位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.POS_CHANNEL
     *
     * @mbg.generated
     */
    private String posChannel;

    /**
     * Database Column Remarks:
     *   公司代碼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.COMPANY_CODE
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     * Database Column Remarks:
     *   排序順序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.SEQUENCE_NUM
     *
     * @mbg.generated
     */
    private Integer sequenceNum;

    /**
     * Database Column Remarks:
     *   SAP下傳CHANNEL編
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.SAP_CHANNEL
     *
     * @mbg.generated
     */
    private String sapChannel;

    /**
     * Database Column Remarks:
     *   楊梅倉
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.DC_STORE_ID
     *
     * @mbg.generated
     */
    private String dcStoreId;

    /**
     * Database Column Remarks:
     *   狀態(A=可用, D=關閉) for 權限設定使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_CHANNEL.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.CHANNEL_ID
     *
     * @return the value of TBL_CHANNEL.CHANNEL_ID
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.CHANNEL_ID
     *
     * @param channelId the value for TBL_CHANNEL.CHANNEL_ID
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.CHANNEL_NAME
     *
     * @return the value of TBL_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.CHANNEL_NAME
     *
     * @param channelName the value for TBL_CHANNEL.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.POS_CHANNEL
     *
     * @return the value of TBL_CHANNEL.POS_CHANNEL
     *
     * @mbg.generated
     */
    public String getPosChannel() {
        return posChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.POS_CHANNEL
     *
     * @param posChannel the value for TBL_CHANNEL.POS_CHANNEL
     *
     * @mbg.generated
     */
    public void setPosChannel(String posChannel) {
        this.posChannel = posChannel == null ? null : posChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.COMPANY_CODE
     *
     * @return the value of TBL_CHANNEL.COMPANY_CODE
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.COMPANY_CODE
     *
     * @param companyCode the value for TBL_CHANNEL.COMPANY_CODE
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.SEQUENCE_NUM
     *
     * @return the value of TBL_CHANNEL.SEQUENCE_NUM
     *
     * @mbg.generated
     */
    public Integer getSequenceNum() {
        return sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.SEQUENCE_NUM
     *
     * @param sequenceNum the value for TBL_CHANNEL.SEQUENCE_NUM
     *
     * @mbg.generated
     */
    public void setSequenceNum(Integer sequenceNum) {
        this.sequenceNum = sequenceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.SAP_CHANNEL
     *
     * @return the value of TBL_CHANNEL.SAP_CHANNEL
     *
     * @mbg.generated
     */
    public String getSapChannel() {
        return sapChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.SAP_CHANNEL
     *
     * @param sapChannel the value for TBL_CHANNEL.SAP_CHANNEL
     *
     * @mbg.generated
     */
    public void setSapChannel(String sapChannel) {
        this.sapChannel = sapChannel == null ? null : sapChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.DC_STORE_ID
     *
     * @return the value of TBL_CHANNEL.DC_STORE_ID
     *
     * @mbg.generated
     */
    public String getDcStoreId() {
        return dcStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.DC_STORE_ID
     *
     * @param dcStoreId the value for TBL_CHANNEL.DC_STORE_ID
     *
     * @mbg.generated
     */
    public void setDcStoreId(String dcStoreId) {
        this.dcStoreId = dcStoreId == null ? null : dcStoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_CHANNEL.STATUS
     *
     * @return the value of TBL_CHANNEL.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_CHANNEL.STATUS
     *
     * @param status the value for TBL_CHANNEL.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", channelId=").append(channelId);
        sb.append(", channelName=").append(channelName);
        sb.append(", posChannel=").append(posChannel);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", sequenceNum=").append(sequenceNum);
        sb.append(", sapChannel=").append(sapChannel);
        sb.append(", dcStoreId=").append(dcStoreId);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Channel other = (Channel) that;
        return (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getChannelName() == null ? other.getChannelName() == null : this.getChannelName().equals(other.getChannelName()))
            && (this.getPosChannel() == null ? other.getPosChannel() == null : this.getPosChannel().equals(other.getPosChannel()))
            && (this.getCompanyCode() == null ? other.getCompanyCode() == null : this.getCompanyCode().equals(other.getCompanyCode()))
            && (this.getSequenceNum() == null ? other.getSequenceNum() == null : this.getSequenceNum().equals(other.getSequenceNum()))
            && (this.getSapChannel() == null ? other.getSapChannel() == null : this.getSapChannel().equals(other.getSapChannel()))
            && (this.getDcStoreId() == null ? other.getDcStoreId() == null : this.getDcStoreId().equals(other.getDcStoreId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_CHANNEL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getChannelName() == null) ? 0 : getChannelName().hashCode());
        result = prime * result + ((getPosChannel() == null) ? 0 : getPosChannel().hashCode());
        result = prime * result + ((getCompanyCode() == null) ? 0 : getCompanyCode().hashCode());
        result = prime * result + ((getSequenceNum() == null) ? 0 : getSequenceNum().hashCode());
        result = prime * result + ((getSapChannel() == null) ? 0 : getSapChannel().hashCode());
        result = prime * result + ((getDcStoreId() == null) ? 0 : getDcStoreId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}