package com.tgfc.som.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class StoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public StoreExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("STORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("STORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(String value) {
            addCriterion("STORE_ID =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(String value) {
            addCriterion("STORE_ID <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(String value) {
            addCriterion("STORE_ID >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ID >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(String value) {
            addCriterion("STORE_ID <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(String value) {
            addCriterion("STORE_ID <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLike(String value) {
            addCriterion("STORE_ID like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotLike(String value) {
            addCriterion("STORE_ID not like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<String> values) {
            addCriterion("STORE_ID in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<String> values) {
            addCriterion("STORE_ID not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(String value1, String value2) {
            addCriterion("STORE_ID between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(String value1, String value2) {
            addCriterion("STORE_ID not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("CHANNEL_ID =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ID <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("CHANNEL_ID >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("CHANNEL_ID <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("CHANNEL_ID like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("CHANNEL_ID not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("CHANNEL_ID in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ID not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("STORE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("STORE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("STORE_NAME =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("STORE_NAME <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("STORE_NAME >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_NAME >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("STORE_NAME <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("STORE_NAME <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("STORE_NAME like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("STORE_NAME not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("STORE_NAME in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("STORE_NAME not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("STORE_NAME between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("STORE_NAME not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNull() {
            addCriterion("SHORT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNotNull() {
            addCriterion("SHORT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andShortNameEqualTo(String value) {
            addCriterion("SHORT_NAME =", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotEqualTo(String value) {
            addCriterion("SHORT_NAME <>", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThan(String value) {
            addCriterion("SHORT_NAME >", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("SHORT_NAME >=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThan(String value) {
            addCriterion("SHORT_NAME <", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThanOrEqualTo(String value) {
            addCriterion("SHORT_NAME <=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLike(String value) {
            addCriterion("SHORT_NAME like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotLike(String value) {
            addCriterion("SHORT_NAME not like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameIn(List<String> values) {
            addCriterion("SHORT_NAME in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotIn(List<String> values) {
            addCriterion("SHORT_NAME not in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameBetween(String value1, String value2) {
            addCriterion("SHORT_NAME between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotBetween(String value1, String value2) {
            addCriterion("SHORT_NAME not between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(LocalDateTime value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(LocalDateTime value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNull() {
            addCriterion("CLOSE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCloseDateIsNotNull() {
            addCriterion("CLOSE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCloseDateEqualTo(LocalDateTime value) {
            addCriterion("CLOSE_DATE =", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotEqualTo(LocalDateTime value) {
            addCriterion("CLOSE_DATE <>", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThan(LocalDateTime value) {
            addCriterion("CLOSE_DATE >", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CLOSE_DATE >=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThan(LocalDateTime value) {
            addCriterion("CLOSE_DATE <", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CLOSE_DATE <=", value, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateIn(List<LocalDateTime> values) {
            addCriterion("CLOSE_DATE in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotIn(List<LocalDateTime> values) {
            addCriterion("CLOSE_DATE not in", values, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CLOSE_DATE between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andCloseDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CLOSE_DATE not between", value1, value2, "closeDate");
            return (Criteria) this;
        }

        public Criteria andStoreAddrIsNull() {
            addCriterion("STORE_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andStoreAddrIsNotNull() {
            addCriterion("STORE_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andStoreAddrEqualTo(String value) {
            addCriterion("STORE_ADDR =", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrNotEqualTo(String value) {
            addCriterion("STORE_ADDR <>", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrGreaterThan(String value) {
            addCriterion("STORE_ADDR >", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ADDR >=", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrLessThan(String value) {
            addCriterion("STORE_ADDR <", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrLessThanOrEqualTo(String value) {
            addCriterion("STORE_ADDR <=", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrLike(String value) {
            addCriterion("STORE_ADDR like", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrNotLike(String value) {
            addCriterion("STORE_ADDR not like", value, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrIn(List<String> values) {
            addCriterion("STORE_ADDR in", values, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrNotIn(List<String> values) {
            addCriterion("STORE_ADDR not in", values, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrBetween(String value1, String value2) {
            addCriterion("STORE_ADDR between", value1, value2, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreAddrNotBetween(String value1, String value2) {
            addCriterion("STORE_ADDR not between", value1, value2, "storeAddr");
            return (Criteria) this;
        }

        public Criteria andStoreTelIsNull() {
            addCriterion("STORE_TEL is null");
            return (Criteria) this;
        }

        public Criteria andStoreTelIsNotNull() {
            addCriterion("STORE_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andStoreTelEqualTo(String value) {
            addCriterion("STORE_TEL =", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelNotEqualTo(String value) {
            addCriterion("STORE_TEL <>", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelGreaterThan(String value) {
            addCriterion("STORE_TEL >", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_TEL >=", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelLessThan(String value) {
            addCriterion("STORE_TEL <", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelLessThanOrEqualTo(String value) {
            addCriterion("STORE_TEL <=", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelLike(String value) {
            addCriterion("STORE_TEL like", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelNotLike(String value) {
            addCriterion("STORE_TEL not like", value, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelIn(List<String> values) {
            addCriterion("STORE_TEL in", values, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelNotIn(List<String> values) {
            addCriterion("STORE_TEL not in", values, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelBetween(String value1, String value2) {
            addCriterion("STORE_TEL between", value1, value2, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreTelNotBetween(String value1, String value2) {
            addCriterion("STORE_TEL not between", value1, value2, "storeTel");
            return (Criteria) this;
        }

        public Criteria andStoreFaxIsNull() {
            addCriterion("STORE_FAX is null");
            return (Criteria) this;
        }

        public Criteria andStoreFaxIsNotNull() {
            addCriterion("STORE_FAX is not null");
            return (Criteria) this;
        }

        public Criteria andStoreFaxEqualTo(String value) {
            addCriterion("STORE_FAX =", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxNotEqualTo(String value) {
            addCriterion("STORE_FAX <>", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxGreaterThan(String value) {
            addCriterion("STORE_FAX >", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_FAX >=", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxLessThan(String value) {
            addCriterion("STORE_FAX <", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxLessThanOrEqualTo(String value) {
            addCriterion("STORE_FAX <=", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxLike(String value) {
            addCriterion("STORE_FAX like", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxNotLike(String value) {
            addCriterion("STORE_FAX not like", value, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxIn(List<String> values) {
            addCriterion("STORE_FAX in", values, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxNotIn(List<String> values) {
            addCriterion("STORE_FAX not in", values, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxBetween(String value1, String value2) {
            addCriterion("STORE_FAX between", value1, value2, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStoreFaxNotBetween(String value1, String value2) {
            addCriterion("STORE_FAX not between", value1, value2, "storeFax");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("\"STATUS\" is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("\"STATUS\" is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("\"STATUS\" =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("\"STATUS\" <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("\"STATUS\" >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("\"STATUS\" >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("\"STATUS\" <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("\"STATUS\" <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("\"STATUS\" like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("\"STATUS\" not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("\"STATUS\" in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("\"STATUS\" not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("\"STATUS\" between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("\"STATUS\" not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("COMPANY_ID like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("COMPANY_ID not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("SITE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("SITE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(String value) {
            addCriterion("SITE_ID =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(String value) {
            addCriterion("SITE_ID <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(String value) {
            addCriterion("SITE_ID >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(String value) {
            addCriterion("SITE_ID >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(String value) {
            addCriterion("SITE_ID <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(String value) {
            addCriterion("SITE_ID <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLike(String value) {
            addCriterion("SITE_ID like", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotLike(String value) {
            addCriterion("SITE_ID not like", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<String> values) {
            addCriterion("SITE_ID in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<String> values) {
            addCriterion("SITE_ID not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(String value1, String value2) {
            addCriterion("SITE_ID between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(String value1, String value2) {
            addCriterion("SITE_ID not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("AREA_ID =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("AREA_ID <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("AREA_ID >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ID >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("AREA_ID <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("AREA_ID <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("AREA_ID like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("AREA_ID not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("AREA_ID in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("AREA_ID not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("AREA_ID between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("AREA_ID not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andCostCenterIsNull() {
            addCriterion("COST_CENTER is null");
            return (Criteria) this;
        }

        public Criteria andCostCenterIsNotNull() {
            addCriterion("COST_CENTER is not null");
            return (Criteria) this;
        }

        public Criteria andCostCenterEqualTo(String value) {
            addCriterion("COST_CENTER =", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterNotEqualTo(String value) {
            addCriterion("COST_CENTER <>", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterGreaterThan(String value) {
            addCriterion("COST_CENTER >", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterGreaterThanOrEqualTo(String value) {
            addCriterion("COST_CENTER >=", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterLessThan(String value) {
            addCriterion("COST_CENTER <", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterLessThanOrEqualTo(String value) {
            addCriterion("COST_CENTER <=", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterLike(String value) {
            addCriterion("COST_CENTER like", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterNotLike(String value) {
            addCriterion("COST_CENTER not like", value, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterIn(List<String> values) {
            addCriterion("COST_CENTER in", values, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterNotIn(List<String> values) {
            addCriterion("COST_CENTER not in", values, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterBetween(String value1, String value2) {
            addCriterion("COST_CENTER between", value1, value2, "costCenter");
            return (Criteria) this;
        }

        public Criteria andCostCenterNotBetween(String value1, String value2) {
            addCriterion("COST_CENTER not between", value1, value2, "costCenter");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("ZIP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("ZIP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("ZIP_CODE =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("ZIP_CODE <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("ZIP_CODE >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("ZIP_CODE <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("ZIP_CODE like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("ZIP_CODE not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("ZIP_CODE in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("ZIP_CODE not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("ZIP_CODE between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("ZIP_CODE not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIsNull() {
            addCriterion("TXN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIsNotNull() {
            addCriterion("TXN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeEqualTo(String value) {
            addCriterion("TXN_TYPE =", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotEqualTo(String value) {
            addCriterion("TXN_TYPE <>", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThan(String value) {
            addCriterion("TXN_TYPE >", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_TYPE >=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThan(String value) {
            addCriterion("TXN_TYPE <", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThanOrEqualTo(String value) {
            addCriterion("TXN_TYPE <=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLike(String value) {
            addCriterion("TXN_TYPE like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotLike(String value) {
            addCriterion("TXN_TYPE not like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIn(List<String> values) {
            addCriterion("TXN_TYPE in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotIn(List<String> values) {
            addCriterion("TXN_TYPE not in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeBetween(String value1, String value2) {
            addCriterion("TXN_TYPE between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotBetween(String value1, String value2) {
            addCriterion("TXN_TYPE not between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeIsNull() {
            addCriterion("STORE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andStoreTypeIsNotNull() {
            addCriterion("STORE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andStoreTypeEqualTo(String value) {
            addCriterion("STORE_TYPE =", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeNotEqualTo(String value) {
            addCriterion("STORE_TYPE <>", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeGreaterThan(String value) {
            addCriterion("STORE_TYPE >", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_TYPE >=", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeLessThan(String value) {
            addCriterion("STORE_TYPE <", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeLessThanOrEqualTo(String value) {
            addCriterion("STORE_TYPE <=", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeLike(String value) {
            addCriterion("STORE_TYPE like", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeNotLike(String value) {
            addCriterion("STORE_TYPE not like", value, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeIn(List<String> values) {
            addCriterion("STORE_TYPE in", values, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeNotIn(List<String> values) {
            addCriterion("STORE_TYPE not in", values, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeBetween(String value1, String value2) {
            addCriterion("STORE_TYPE between", value1, value2, "storeType");
            return (Criteria) this;
        }

        public Criteria andStoreTypeNotBetween(String value1, String value2) {
            addCriterion("STORE_TYPE not between", value1, value2, "storeType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeIsNull() {
            addCriterion("GUI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andGuiTypeIsNotNull() {
            addCriterion("GUI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andGuiTypeEqualTo(String value) {
            addCriterion("GUI_TYPE =", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeNotEqualTo(String value) {
            addCriterion("GUI_TYPE <>", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeGreaterThan(String value) {
            addCriterion("GUI_TYPE >", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("GUI_TYPE >=", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeLessThan(String value) {
            addCriterion("GUI_TYPE <", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeLessThanOrEqualTo(String value) {
            addCriterion("GUI_TYPE <=", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeLike(String value) {
            addCriterion("GUI_TYPE like", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeNotLike(String value) {
            addCriterion("GUI_TYPE not like", value, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeIn(List<String> values) {
            addCriterion("GUI_TYPE in", values, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeNotIn(List<String> values) {
            addCriterion("GUI_TYPE not in", values, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeBetween(String value1, String value2) {
            addCriterion("GUI_TYPE between", value1, value2, "guiType");
            return (Criteria) this;
        }

        public Criteria andGuiTypeNotBetween(String value1, String value2) {
            addCriterion("GUI_TYPE not between", value1, value2, "guiType");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameIsNull() {
            addCriterion("POS_STORE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameIsNotNull() {
            addCriterion("POS_STORE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameEqualTo(String value) {
            addCriterion("POS_STORE_NAME =", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameNotEqualTo(String value) {
            addCriterion("POS_STORE_NAME <>", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameGreaterThan(String value) {
            addCriterion("POS_STORE_NAME >", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("POS_STORE_NAME >=", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameLessThan(String value) {
            addCriterion("POS_STORE_NAME <", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameLessThanOrEqualTo(String value) {
            addCriterion("POS_STORE_NAME <=", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameLike(String value) {
            addCriterion("POS_STORE_NAME like", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameNotLike(String value) {
            addCriterion("POS_STORE_NAME not like", value, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameIn(List<String> values) {
            addCriterion("POS_STORE_NAME in", values, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameNotIn(List<String> values) {
            addCriterion("POS_STORE_NAME not in", values, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameBetween(String value1, String value2) {
            addCriterion("POS_STORE_NAME between", value1, value2, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andPosStoreNameNotBetween(String value1, String value2) {
            addCriterion("POS_STORE_NAME not between", value1, value2, "posStoreName");
            return (Criteria) this;
        }

        public Criteria andInvTitleIsNull() {
            addCriterion("INV_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andInvTitleIsNotNull() {
            addCriterion("INV_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andInvTitleEqualTo(String value) {
            addCriterion("INV_TITLE =", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleNotEqualTo(String value) {
            addCriterion("INV_TITLE <>", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleGreaterThan(String value) {
            addCriterion("INV_TITLE >", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleGreaterThanOrEqualTo(String value) {
            addCriterion("INV_TITLE >=", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleLessThan(String value) {
            addCriterion("INV_TITLE <", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleLessThanOrEqualTo(String value) {
            addCriterion("INV_TITLE <=", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleLike(String value) {
            addCriterion("INV_TITLE like", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleNotLike(String value) {
            addCriterion("INV_TITLE not like", value, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleIn(List<String> values) {
            addCriterion("INV_TITLE in", values, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleNotIn(List<String> values) {
            addCriterion("INV_TITLE not in", values, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleBetween(String value1, String value2) {
            addCriterion("INV_TITLE between", value1, value2, "invTitle");
            return (Criteria) this;
        }

        public Criteria andInvTitleNotBetween(String value1, String value2) {
            addCriterion("INV_TITLE not between", value1, value2, "invTitle");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailIsNull() {
            addCriterion("TTS_AUTO_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailIsNotNull() {
            addCriterion("TTS_AUTO_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailEqualTo(String value) {
            addCriterion("TTS_AUTO_EMAIL =", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailNotEqualTo(String value) {
            addCriterion("TTS_AUTO_EMAIL <>", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailGreaterThan(String value) {
            addCriterion("TTS_AUTO_EMAIL >", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailGreaterThanOrEqualTo(String value) {
            addCriterion("TTS_AUTO_EMAIL >=", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailLessThan(String value) {
            addCriterion("TTS_AUTO_EMAIL <", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailLessThanOrEqualTo(String value) {
            addCriterion("TTS_AUTO_EMAIL <=", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailLike(String value) {
            addCriterion("TTS_AUTO_EMAIL like", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailNotLike(String value) {
            addCriterion("TTS_AUTO_EMAIL not like", value, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailIn(List<String> values) {
            addCriterion("TTS_AUTO_EMAIL in", values, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailNotIn(List<String> values) {
            addCriterion("TTS_AUTO_EMAIL not in", values, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailBetween(String value1, String value2) {
            addCriterion("TTS_AUTO_EMAIL between", value1, value2, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andTtsAutoEmailNotBetween(String value1, String value2) {
            addCriterion("TTS_AUTO_EMAIL not between", value1, value2, "ttsAutoEmail");
            return (Criteria) this;
        }

        public Criteria andHctIdIsNull() {
            addCriterion("HCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andHctIdIsNotNull() {
            addCriterion("HCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHctIdEqualTo(String value) {
            addCriterion("HCT_ID =", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdNotEqualTo(String value) {
            addCriterion("HCT_ID <>", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdGreaterThan(String value) {
            addCriterion("HCT_ID >", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdGreaterThanOrEqualTo(String value) {
            addCriterion("HCT_ID >=", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdLessThan(String value) {
            addCriterion("HCT_ID <", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdLessThanOrEqualTo(String value) {
            addCriterion("HCT_ID <=", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdLike(String value) {
            addCriterion("HCT_ID like", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdNotLike(String value) {
            addCriterion("HCT_ID not like", value, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdIn(List<String> values) {
            addCriterion("HCT_ID in", values, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdNotIn(List<String> values) {
            addCriterion("HCT_ID not in", values, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdBetween(String value1, String value2) {
            addCriterion("HCT_ID between", value1, value2, "hctId");
            return (Criteria) this;
        }

        public Criteria andHctIdNotBetween(String value1, String value2) {
            addCriterion("HCT_ID not between", value1, value2, "hctId");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailIsNull() {
            addCriterion("PAYPAGE_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailIsNotNull() {
            addCriterion("PAYPAGE_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailEqualTo(String value) {
            addCriterion("PAYPAGE_EMAIL =", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailNotEqualTo(String value) {
            addCriterion("PAYPAGE_EMAIL <>", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailGreaterThan(String value) {
            addCriterion("PAYPAGE_EMAIL >", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailGreaterThanOrEqualTo(String value) {
            addCriterion("PAYPAGE_EMAIL >=", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailLessThan(String value) {
            addCriterion("PAYPAGE_EMAIL <", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailLessThanOrEqualTo(String value) {
            addCriterion("PAYPAGE_EMAIL <=", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailLike(String value) {
            addCriterion("PAYPAGE_EMAIL like", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailNotLike(String value) {
            addCriterion("PAYPAGE_EMAIL not like", value, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailIn(List<String> values) {
            addCriterion("PAYPAGE_EMAIL in", values, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailNotIn(List<String> values) {
            addCriterion("PAYPAGE_EMAIL not in", values, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailBetween(String value1, String value2) {
            addCriterion("PAYPAGE_EMAIL between", value1, value2, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andPaypageEmailNotBetween(String value1, String value2) {
            addCriterion("PAYPAGE_EMAIL not between", value1, value2, "paypageEmail");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyIsNull() {
            addCriterion("JSGO_KEY is null");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyIsNotNull() {
            addCriterion("JSGO_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyEqualTo(String value) {
            addCriterion("JSGO_KEY =", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyNotEqualTo(String value) {
            addCriterion("JSGO_KEY <>", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyGreaterThan(String value) {
            addCriterion("JSGO_KEY >", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyGreaterThanOrEqualTo(String value) {
            addCriterion("JSGO_KEY >=", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyLessThan(String value) {
            addCriterion("JSGO_KEY <", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyLessThanOrEqualTo(String value) {
            addCriterion("JSGO_KEY <=", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyLike(String value) {
            addCriterion("JSGO_KEY like", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyNotLike(String value) {
            addCriterion("JSGO_KEY not like", value, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyIn(List<String> values) {
            addCriterion("JSGO_KEY in", values, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyNotIn(List<String> values) {
            addCriterion("JSGO_KEY not in", values, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyBetween(String value1, String value2) {
            addCriterion("JSGO_KEY between", value1, value2, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andJsgoKeyNotBetween(String value1, String value2) {
            addCriterion("JSGO_KEY not between", value1, value2, "jsgoKey");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdIsNull() {
            addCriterion("UPDATE_EMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdIsNotNull() {
            addCriterion("UPDATE_EMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdEqualTo(String value) {
            addCriterion("UPDATE_EMP_ID =", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdNotEqualTo(String value) {
            addCriterion("UPDATE_EMP_ID <>", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdGreaterThan(String value) {
            addCriterion("UPDATE_EMP_ID >", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_ID >=", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdLessThan(String value) {
            addCriterion("UPDATE_EMP_ID <", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_ID <=", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdLike(String value) {
            addCriterion("UPDATE_EMP_ID like", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdNotLike(String value) {
            addCriterion("UPDATE_EMP_ID not like", value, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdIn(List<String> values) {
            addCriterion("UPDATE_EMP_ID in", values, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdNotIn(List<String> values) {
            addCriterion("UPDATE_EMP_ID not in", values, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_ID between", value1, value2, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_ID not between", value1, value2, "updateEmpId");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameIsNull() {
            addCriterion("UPDATE_EMP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameIsNotNull() {
            addCriterion("UPDATE_EMP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameEqualTo(String value) {
            addCriterion("UPDATE_EMP_NAME =", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameNotEqualTo(String value) {
            addCriterion("UPDATE_EMP_NAME <>", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameGreaterThan(String value) {
            addCriterion("UPDATE_EMP_NAME >", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_NAME >=", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameLessThan(String value) {
            addCriterion("UPDATE_EMP_NAME <", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_EMP_NAME <=", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameLike(String value) {
            addCriterion("UPDATE_EMP_NAME like", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameNotLike(String value) {
            addCriterion("UPDATE_EMP_NAME not like", value, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameIn(List<String> values) {
            addCriterion("UPDATE_EMP_NAME in", values, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameNotIn(List<String> values) {
            addCriterion("UPDATE_EMP_NAME not in", values, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_NAME between", value1, value2, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andUpdateEmpNameNotBetween(String value1, String value2) {
            addCriterion("UPDATE_EMP_NAME not between", value1, value2, "updateEmpName");
            return (Criteria) this;
        }

        public Criteria andShowFlagIsNull() {
            addCriterion("SHOW_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andShowFlagIsNotNull() {
            addCriterion("SHOW_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andShowFlagEqualTo(String value) {
            addCriterion("SHOW_FLAG =", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagNotEqualTo(String value) {
            addCriterion("SHOW_FLAG <>", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagGreaterThan(String value) {
            addCriterion("SHOW_FLAG >", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SHOW_FLAG >=", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagLessThan(String value) {
            addCriterion("SHOW_FLAG <", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagLessThanOrEqualTo(String value) {
            addCriterion("SHOW_FLAG <=", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagLike(String value) {
            addCriterion("SHOW_FLAG like", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagNotLike(String value) {
            addCriterion("SHOW_FLAG not like", value, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagIn(List<String> values) {
            addCriterion("SHOW_FLAG in", values, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagNotIn(List<String> values) {
            addCriterion("SHOW_FLAG not in", values, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagBetween(String value1, String value2) {
            addCriterion("SHOW_FLAG between", value1, value2, "showFlag");
            return (Criteria) this;
        }

        public Criteria andShowFlagNotBetween(String value1, String value2) {
            addCriterion("SHOW_FLAG not between", value1, value2, "showFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_STORE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}