package com.tgfc.som.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_STORE
 */
public class Store implements Serializable {
    /**
     * Database Column Remarks:
     *   店別代號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_ID
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     * Database Column Remarks:
     *   通路別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   店名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_NAME
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     * Database Column Remarks:
     *   門店英文簡碼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.SHORT_NAME
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     * Database Column Remarks:
     *   建立日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.CREATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     * Database Column Remarks:
     *   關店日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.CLOSE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime closeDate;

    /**
     * Database Column Remarks:
     *   店址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_ADDR
     *
     * @mbg.generated
     */
    private String storeAddr;

    /**
     * Database Column Remarks:
     *   門店電話
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_TEL
     *
     * @mbg.generated
     */
    private String storeTel;

    /**
     * Database Column Remarks:
     *   門店傳真
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_FAX
     *
     * @mbg.generated
     */
    private String storeFax;

    /**
     * Database Column Remarks:
     *   狀態(A: 可用, D: 關店(系統不可用，但可關聯))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   統一編號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.COMPANY_ID
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   門店在 SAP 上的 SITE ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.SITE_ID
     *
     * @mbg.generated
     */
    private String siteId;

    /**
     * Database Column Remarks:
     *   店所屬的區域(001: 北區, 002: 中區, 003: 南區)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.AREA_ID
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     * Database Column Remarks:
     *   成本中心
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.COST_CENTER
     *
     * @mbg.generated
     */
    private String costCenter;

    /**
     * Database Column Remarks:
     *   郵遞區號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.ZIP_CODE
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   交易類型	10:百貨專櫃, 11:自營門市, 12:批發, 13:特賣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.TXN_TYPE
     *
     * @mbg.generated
     */
    private String txnType;

    /**
     * Database Column Remarks:
     *   店別類型	1: 一般實體店(SAP: A), 2: 倉庫(SAP: B), 3: 非實體店, 4: 其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.STORE_TYPE
     *
     * @mbg.generated
     */
    private String storeType;

    /**
     * Database Column Remarks:
     *   發票類型	0: 電子發票 1:舊式發票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.GUI_TYPE
     *
     * @mbg.generated
     */
    private String guiType;

    /**
     * Database Column Remarks:
     *   門店電子郵件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   POS店名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.POS_STORE_NAME
     *
     * @mbg.generated
     */
    private String posStoreName;

    /**
     * Database Column Remarks:
     *   發票公司抬頭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.INV_TITLE
     *
     * @mbg.generated
     */
    private String invTitle;

    /**
     * Database Column Remarks:
     *   TTS自動化報表收件人郵件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.TTS_AUTO_EMAIL
     *
     * @mbg.generated
     */
    private String ttsAutoEmail;

    /**
     * Database Column Remarks:
     *   新竹貨運客店代碼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.HCT_ID
     *
     * @mbg.generated
     */
    private String hctId;

    /**
     * Database Column Remarks:
     *   Paypage付款完成後通知門店信箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.PAYPAGE_EMAIL
     *
     * @mbg.generated
     */
    private String paypageEmail;

    /**
     * Database Column Remarks:
     *   來速捷Key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.JSGO_KEY
     *
     * @mbg.generated
     */
    private String jsgoKey;

    /**
     * Database Column Remarks:
     *   最後異動日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * Database Column Remarks:
     *   最後異動者工號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    private String updateEmpId;

    /**
     * Database Column Remarks:
     *   最後異動者名稱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    private String updateEmpName;

    /**
     * Database Column Remarks:
     *   跨店訂單查詢-結帳店是否顯示在下拉清單 (Y:出現 N:不出現)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_STORE.SHOW_FLAG
     *
     * @mbg.generated
     */
    private String showFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_ID
     *
     * @return the value of TBL_STORE.STORE_ID
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_ID
     *
     * @param storeId the value for TBL_STORE.STORE_ID
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.CHANNEL_ID
     *
     * @return the value of TBL_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.CHANNEL_ID
     *
     * @param channelId the value for TBL_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_NAME
     *
     * @return the value of TBL_STORE.STORE_NAME
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_NAME
     *
     * @param storeName the value for TBL_STORE.STORE_NAME
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.SHORT_NAME
     *
     * @return the value of TBL_STORE.SHORT_NAME
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.SHORT_NAME
     *
     * @param shortName the value for TBL_STORE.SHORT_NAME
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.CREATE_DATE
     *
     * @return the value of TBL_STORE.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.CREATE_DATE
     *
     * @param createDate the value for TBL_STORE.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.CLOSE_DATE
     *
     * @return the value of TBL_STORE.CLOSE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getCloseDate() {
        return closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.CLOSE_DATE
     *
     * @param closeDate the value for TBL_STORE.CLOSE_DATE
     *
     * @mbg.generated
     */
    public void setCloseDate(LocalDateTime closeDate) {
        this.closeDate = closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_ADDR
     *
     * @return the value of TBL_STORE.STORE_ADDR
     *
     * @mbg.generated
     */
    public String getStoreAddr() {
        return storeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_ADDR
     *
     * @param storeAddr the value for TBL_STORE.STORE_ADDR
     *
     * @mbg.generated
     */
    public void setStoreAddr(String storeAddr) {
        this.storeAddr = storeAddr == null ? null : storeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_TEL
     *
     * @return the value of TBL_STORE.STORE_TEL
     *
     * @mbg.generated
     */
    public String getStoreTel() {
        return storeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_TEL
     *
     * @param storeTel the value for TBL_STORE.STORE_TEL
     *
     * @mbg.generated
     */
    public void setStoreTel(String storeTel) {
        this.storeTel = storeTel == null ? null : storeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_FAX
     *
     * @return the value of TBL_STORE.STORE_FAX
     *
     * @mbg.generated
     */
    public String getStoreFax() {
        return storeFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_FAX
     *
     * @param storeFax the value for TBL_STORE.STORE_FAX
     *
     * @mbg.generated
     */
    public void setStoreFax(String storeFax) {
        this.storeFax = storeFax == null ? null : storeFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STATUS
     *
     * @return the value of TBL_STORE.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STATUS
     *
     * @param status the value for TBL_STORE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.COMPANY_ID
     *
     * @return the value of TBL_STORE.COMPANY_ID
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.COMPANY_ID
     *
     * @param companyId the value for TBL_STORE.COMPANY_ID
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.SITE_ID
     *
     * @return the value of TBL_STORE.SITE_ID
     *
     * @mbg.generated
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.SITE_ID
     *
     * @param siteId the value for TBL_STORE.SITE_ID
     *
     * @mbg.generated
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.AREA_ID
     *
     * @return the value of TBL_STORE.AREA_ID
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.AREA_ID
     *
     * @param areaId the value for TBL_STORE.AREA_ID
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.COST_CENTER
     *
     * @return the value of TBL_STORE.COST_CENTER
     *
     * @mbg.generated
     */
    public String getCostCenter() {
        return costCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.COST_CENTER
     *
     * @param costCenter the value for TBL_STORE.COST_CENTER
     *
     * @mbg.generated
     */
    public void setCostCenter(String costCenter) {
        this.costCenter = costCenter == null ? null : costCenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.ZIP_CODE
     *
     * @return the value of TBL_STORE.ZIP_CODE
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.ZIP_CODE
     *
     * @param zipCode the value for TBL_STORE.ZIP_CODE
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.TXN_TYPE
     *
     * @return the value of TBL_STORE.TXN_TYPE
     *
     * @mbg.generated
     */
    public String getTxnType() {
        return txnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.TXN_TYPE
     *
     * @param txnType the value for TBL_STORE.TXN_TYPE
     *
     * @mbg.generated
     */
    public void setTxnType(String txnType) {
        this.txnType = txnType == null ? null : txnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.STORE_TYPE
     *
     * @return the value of TBL_STORE.STORE_TYPE
     *
     * @mbg.generated
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.STORE_TYPE
     *
     * @param storeType the value for TBL_STORE.STORE_TYPE
     *
     * @mbg.generated
     */
    public void setStoreType(String storeType) {
        this.storeType = storeType == null ? null : storeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.GUI_TYPE
     *
     * @return the value of TBL_STORE.GUI_TYPE
     *
     * @mbg.generated
     */
    public String getGuiType() {
        return guiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.GUI_TYPE
     *
     * @param guiType the value for TBL_STORE.GUI_TYPE
     *
     * @mbg.generated
     */
    public void setGuiType(String guiType) {
        this.guiType = guiType == null ? null : guiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.EMAIL
     *
     * @return the value of TBL_STORE.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.EMAIL
     *
     * @param email the value for TBL_STORE.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.POS_STORE_NAME
     *
     * @return the value of TBL_STORE.POS_STORE_NAME
     *
     * @mbg.generated
     */
    public String getPosStoreName() {
        return posStoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.POS_STORE_NAME
     *
     * @param posStoreName the value for TBL_STORE.POS_STORE_NAME
     *
     * @mbg.generated
     */
    public void setPosStoreName(String posStoreName) {
        this.posStoreName = posStoreName == null ? null : posStoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.INV_TITLE
     *
     * @return the value of TBL_STORE.INV_TITLE
     *
     * @mbg.generated
     */
    public String getInvTitle() {
        return invTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.INV_TITLE
     *
     * @param invTitle the value for TBL_STORE.INV_TITLE
     *
     * @mbg.generated
     */
    public void setInvTitle(String invTitle) {
        this.invTitle = invTitle == null ? null : invTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.TTS_AUTO_EMAIL
     *
     * @return the value of TBL_STORE.TTS_AUTO_EMAIL
     *
     * @mbg.generated
     */
    public String getTtsAutoEmail() {
        return ttsAutoEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.TTS_AUTO_EMAIL
     *
     * @param ttsAutoEmail the value for TBL_STORE.TTS_AUTO_EMAIL
     *
     * @mbg.generated
     */
    public void setTtsAutoEmail(String ttsAutoEmail) {
        this.ttsAutoEmail = ttsAutoEmail == null ? null : ttsAutoEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.HCT_ID
     *
     * @return the value of TBL_STORE.HCT_ID
     *
     * @mbg.generated
     */
    public String getHctId() {
        return hctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.HCT_ID
     *
     * @param hctId the value for TBL_STORE.HCT_ID
     *
     * @mbg.generated
     */
    public void setHctId(String hctId) {
        this.hctId = hctId == null ? null : hctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.PAYPAGE_EMAIL
     *
     * @return the value of TBL_STORE.PAYPAGE_EMAIL
     *
     * @mbg.generated
     */
    public String getPaypageEmail() {
        return paypageEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.PAYPAGE_EMAIL
     *
     * @param paypageEmail the value for TBL_STORE.PAYPAGE_EMAIL
     *
     * @mbg.generated
     */
    public void setPaypageEmail(String paypageEmail) {
        this.paypageEmail = paypageEmail == null ? null : paypageEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.JSGO_KEY
     *
     * @return the value of TBL_STORE.JSGO_KEY
     *
     * @mbg.generated
     */
    public String getJsgoKey() {
        return jsgoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.JSGO_KEY
     *
     * @param jsgoKey the value for TBL_STORE.JSGO_KEY
     *
     * @mbg.generated
     */
    public void setJsgoKey(String jsgoKey) {
        this.jsgoKey = jsgoKey == null ? null : jsgoKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.UPDATE_DATE
     *
     * @return the value of TBL_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.UPDATE_DATE
     *
     * @param updateDate the value for TBL_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.UPDATE_EMP_ID
     *
     * @return the value of TBL_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public String getUpdateEmpId() {
        return updateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.UPDATE_EMP_ID
     *
     * @param updateEmpId the value for TBL_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public void setUpdateEmpId(String updateEmpId) {
        this.updateEmpId = updateEmpId == null ? null : updateEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.UPDATE_EMP_NAME
     *
     * @return the value of TBL_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public String getUpdateEmpName() {
        return updateEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.UPDATE_EMP_NAME
     *
     * @param updateEmpName the value for TBL_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public void setUpdateEmpName(String updateEmpName) {
        this.updateEmpName = updateEmpName == null ? null : updateEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_STORE.SHOW_FLAG
     *
     * @return the value of TBL_STORE.SHOW_FLAG
     *
     * @mbg.generated
     */
    public String getShowFlag() {
        return showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_STORE.SHOW_FLAG
     *
     * @param showFlag the value for TBL_STORE.SHOW_FLAG
     *
     * @mbg.generated
     */
    public void setShowFlag(String showFlag) {
        this.showFlag = showFlag == null ? null : showFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", storeId=").append(storeId);
        sb.append(", channelId=").append(channelId);
        sb.append(", storeName=").append(storeName);
        sb.append(", shortName=").append(shortName);
        sb.append(", createDate=").append(createDate);
        sb.append(", closeDate=").append(closeDate);
        sb.append(", storeAddr=").append(storeAddr);
        sb.append(", storeTel=").append(storeTel);
        sb.append(", storeFax=").append(storeFax);
        sb.append(", status=").append(status);
        sb.append(", companyId=").append(companyId);
        sb.append(", siteId=").append(siteId);
        sb.append(", areaId=").append(areaId);
        sb.append(", costCenter=").append(costCenter);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", txnType=").append(txnType);
        sb.append(", storeType=").append(storeType);
        sb.append(", guiType=").append(guiType);
        sb.append(", email=").append(email);
        sb.append(", posStoreName=").append(posStoreName);
        sb.append(", invTitle=").append(invTitle);
        sb.append(", ttsAutoEmail=").append(ttsAutoEmail);
        sb.append(", hctId=").append(hctId);
        sb.append(", paypageEmail=").append(paypageEmail);
        sb.append(", jsgoKey=").append(jsgoKey);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateEmpId=").append(updateEmpId);
        sb.append(", updateEmpName=").append(updateEmpName);
        sb.append(", showFlag=").append(showFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Store other = (Store) that;
        return (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getStoreName() == null ? other.getStoreName() == null : this.getStoreName().equals(other.getStoreName()))
            && (this.getShortName() == null ? other.getShortName() == null : this.getShortName().equals(other.getShortName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCloseDate() == null ? other.getCloseDate() == null : this.getCloseDate().equals(other.getCloseDate()))
            && (this.getStoreAddr() == null ? other.getStoreAddr() == null : this.getStoreAddr().equals(other.getStoreAddr()))
            && (this.getStoreTel() == null ? other.getStoreTel() == null : this.getStoreTel().equals(other.getStoreTel()))
            && (this.getStoreFax() == null ? other.getStoreFax() == null : this.getStoreFax().equals(other.getStoreFax()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getSiteId() == null ? other.getSiteId() == null : this.getSiteId().equals(other.getSiteId()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getCostCenter() == null ? other.getCostCenter() == null : this.getCostCenter().equals(other.getCostCenter()))
            && (this.getZipCode() == null ? other.getZipCode() == null : this.getZipCode().equals(other.getZipCode()))
            && (this.getTxnType() == null ? other.getTxnType() == null : this.getTxnType().equals(other.getTxnType()))
            && (this.getStoreType() == null ? other.getStoreType() == null : this.getStoreType().equals(other.getStoreType()))
            && (this.getGuiType() == null ? other.getGuiType() == null : this.getGuiType().equals(other.getGuiType()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPosStoreName() == null ? other.getPosStoreName() == null : this.getPosStoreName().equals(other.getPosStoreName()))
            && (this.getInvTitle() == null ? other.getInvTitle() == null : this.getInvTitle().equals(other.getInvTitle()))
            && (this.getTtsAutoEmail() == null ? other.getTtsAutoEmail() == null : this.getTtsAutoEmail().equals(other.getTtsAutoEmail()))
            && (this.getHctId() == null ? other.getHctId() == null : this.getHctId().equals(other.getHctId()))
            && (this.getPaypageEmail() == null ? other.getPaypageEmail() == null : this.getPaypageEmail().equals(other.getPaypageEmail()))
            && (this.getJsgoKey() == null ? other.getJsgoKey() == null : this.getJsgoKey().equals(other.getJsgoKey()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateEmpId() == null ? other.getUpdateEmpId() == null : this.getUpdateEmpId().equals(other.getUpdateEmpId()))
            && (this.getUpdateEmpName() == null ? other.getUpdateEmpName() == null : this.getUpdateEmpName().equals(other.getUpdateEmpName()))
            && (this.getShowFlag() == null ? other.getShowFlag() == null : this.getShowFlag().equals(other.getShowFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_STORE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getStoreName() == null) ? 0 : getStoreName().hashCode());
        result = prime * result + ((getShortName() == null) ? 0 : getShortName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCloseDate() == null) ? 0 : getCloseDate().hashCode());
        result = prime * result + ((getStoreAddr() == null) ? 0 : getStoreAddr().hashCode());
        result = prime * result + ((getStoreTel() == null) ? 0 : getStoreTel().hashCode());
        result = prime * result + ((getStoreFax() == null) ? 0 : getStoreFax().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getSiteId() == null) ? 0 : getSiteId().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getCostCenter() == null) ? 0 : getCostCenter().hashCode());
        result = prime * result + ((getZipCode() == null) ? 0 : getZipCode().hashCode());
        result = prime * result + ((getTxnType() == null) ? 0 : getTxnType().hashCode());
        result = prime * result + ((getStoreType() == null) ? 0 : getStoreType().hashCode());
        result = prime * result + ((getGuiType() == null) ? 0 : getGuiType().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPosStoreName() == null) ? 0 : getPosStoreName().hashCode());
        result = prime * result + ((getInvTitle() == null) ? 0 : getInvTitle().hashCode());
        result = prime * result + ((getTtsAutoEmail() == null) ? 0 : getTtsAutoEmail().hashCode());
        result = prime * result + ((getHctId() == null) ? 0 : getHctId().hashCode());
        result = prime * result + ((getPaypageEmail() == null) ? 0 : getPaypageEmail().hashCode());
        result = prime * result + ((getJsgoKey() == null) ? 0 : getJsgoKey().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateEmpId() == null) ? 0 : getUpdateEmpId().hashCode());
        result = prime * result + ((getUpdateEmpName() == null) ? 0 : getUpdateEmpName().hashCode());
        result = prime * result + ((getShowFlag() == null) ? 0 : getShowFlag().hashCode());
        return result;
    }
}