package com.tgfc.som.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TblOrderComputeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public TblOrderComputeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andComputeTypeIsNull() {
            addCriterion("COMPUTE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andComputeTypeIsNotNull() {
            addCriterion("COMPUTE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andComputeTypeEqualTo(String value) {
            addCriterion("COMPUTE_TYPE =", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeNotEqualTo(String value) {
            addCriterion("COMPUTE_TYPE <>", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeGreaterThan(String value) {
            addCriterion("COMPUTE_TYPE >", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("COMPUTE_TYPE >=", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeLessThan(String value) {
            addCriterion("COMPUTE_TYPE <", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeLessThanOrEqualTo(String value) {
            addCriterion("COMPUTE_TYPE <=", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeLike(String value) {
            addCriterion("COMPUTE_TYPE like", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeNotLike(String value) {
            addCriterion("COMPUTE_TYPE not like", value, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeIn(List<String> values) {
            addCriterion("COMPUTE_TYPE in", values, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeNotIn(List<String> values) {
            addCriterion("COMPUTE_TYPE not in", values, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeBetween(String value1, String value2) {
            addCriterion("COMPUTE_TYPE between", value1, value2, "computeType");
            return (Criteria) this;
        }

        public Criteria andComputeTypeNotBetween(String value1, String value2) {
            addCriterion("COMPUTE_TYPE not between", value1, value2, "computeType");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("STORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("STORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(String value) {
            addCriterion("STORE_ID =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(String value) {
            addCriterion("STORE_ID <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(String value) {
            addCriterion("STORE_ID >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ID >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(String value) {
            addCriterion("STORE_ID <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(String value) {
            addCriterion("STORE_ID <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLike(String value) {
            addCriterion("STORE_ID like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotLike(String value) {
            addCriterion("STORE_ID not like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<String> values) {
            addCriterion("STORE_ID in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<String> values) {
            addCriterion("STORE_ID not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(String value1, String value2) {
            addCriterion("STORE_ID between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(String value1, String value2) {
            addCriterion("STORE_ID not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<BigDecimal> values) {
            addCriterion("TOTAL_PRICE in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("TOTAL_PRICE not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("DISCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("DISCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(BigDecimal value) {
            addCriterion("DISCOUNT >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(BigDecimal value) {
            addCriterion("DISCOUNT <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<BigDecimal> values) {
            addCriterion("DISCOUNT in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<BigDecimal> values) {
            addCriterion("DISCOUNT not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceIsNull() {
            addCriterion("ACT_TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceIsNotNull() {
            addCriterion("ACT_TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE =", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE <>", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE >", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE >=", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceLessThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE <", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE <=", value, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE in", values, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE not in", values, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE between", value1, value2, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE not between", value1, value2, "actTotalPrice");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxIsNull() {
            addCriterion("ACT_TOTAL_PRICE_TX is null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxIsNotNull() {
            addCriterion("ACT_TOTAL_PRICE_TX is not null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX =", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxNotEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX <>", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxGreaterThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX >", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX >=", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxLessThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX <", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_TX <=", value, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE_TX in", values, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxNotIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE_TX not in", values, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE_TX between", value1, value2, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceTxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE_TX not between", value1, value2, "actTotalPriceTx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxIsNull() {
            addCriterion("ACT_TOTAL_PRICE_NTX is null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxIsNotNull() {
            addCriterion("ACT_TOTAL_PRICE_NTX is not null");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX =", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxNotEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX <>", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxGreaterThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX >", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX >=", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxLessThan(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX <", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_TOTAL_PRICE_NTX <=", value, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE_NTX in", values, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxNotIn(List<BigDecimal> values) {
            addCriterion("ACT_TOTAL_PRICE_NTX not in", values, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE_NTX between", value1, value2, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andActTotalPriceNtxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_TOTAL_PRICE_NTX not between", value1, value2, "actTotalPriceNtx");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdIsNull() {
            addCriterion("AUTHORIZED_EMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdIsNotNull() {
            addCriterion("AUTHORIZED_EMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_ID =", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdNotEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_ID <>", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdGreaterThan(String value) {
            addCriterion("AUTHORIZED_EMP_ID >", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_ID >=", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdLessThan(String value) {
            addCriterion("AUTHORIZED_EMP_ID <", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdLessThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_ID <=", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdLike(String value) {
            addCriterion("AUTHORIZED_EMP_ID like", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdNotLike(String value) {
            addCriterion("AUTHORIZED_EMP_ID not like", value, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdIn(List<String> values) {
            addCriterion("AUTHORIZED_EMP_ID in", values, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdNotIn(List<String> values) {
            addCriterion("AUTHORIZED_EMP_ID not in", values, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_EMP_ID between", value1, value2, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpIdNotBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_EMP_ID not between", value1, value2, "authorizedEmpId");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameIsNull() {
            addCriterion("AUTHORIZED_EMP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameIsNotNull() {
            addCriterion("AUTHORIZED_EMP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_NAME =", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameNotEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_NAME <>", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameGreaterThan(String value) {
            addCriterion("AUTHORIZED_EMP_NAME >", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_NAME >=", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameLessThan(String value) {
            addCriterion("AUTHORIZED_EMP_NAME <", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameLessThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_EMP_NAME <=", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameLike(String value) {
            addCriterion("AUTHORIZED_EMP_NAME like", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameNotLike(String value) {
            addCriterion("AUTHORIZED_EMP_NAME not like", value, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameIn(List<String> values) {
            addCriterion("AUTHORIZED_EMP_NAME in", values, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameNotIn(List<String> values) {
            addCriterion("AUTHORIZED_EMP_NAME not in", values, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_EMP_NAME between", value1, value2, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEmpNameNotBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_EMP_NAME not between", value1, value2, "authorizedEmpName");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonIsNull() {
            addCriterion("AUTHORIZED_REASON is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonIsNotNull() {
            addCriterion("AUTHORIZED_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonEqualTo(String value) {
            addCriterion("AUTHORIZED_REASON =", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonNotEqualTo(String value) {
            addCriterion("AUTHORIZED_REASON <>", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonGreaterThan(String value) {
            addCriterion("AUTHORIZED_REASON >", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_REASON >=", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonLessThan(String value) {
            addCriterion("AUTHORIZED_REASON <", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonLessThanOrEqualTo(String value) {
            addCriterion("AUTHORIZED_REASON <=", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonLike(String value) {
            addCriterion("AUTHORIZED_REASON like", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonNotLike(String value) {
            addCriterion("AUTHORIZED_REASON not like", value, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonIn(List<String> values) {
            addCriterion("AUTHORIZED_REASON in", values, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonNotIn(List<String> values) {
            addCriterion("AUTHORIZED_REASON not in", values, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_REASON between", value1, value2, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andAuthorizedReasonNotBetween(String value1, String value2) {
            addCriterion("AUTHORIZED_REASON not between", value1, value2, "authorizedReason");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateIsNull() {
            addCriterion("AUTHORIZED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateIsNotNull() {
            addCriterion("AUTHORIZED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateEqualTo(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE =", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateNotEqualTo(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE <>", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateGreaterThan(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE >", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE >=", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateLessThan(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE <", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("AUTHORIZED_DATE <=", value, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateIn(List<LocalDateTime> values) {
            addCriterion("AUTHORIZED_DATE in", values, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateNotIn(List<LocalDateTime> values) {
            addCriterion("AUTHORIZED_DATE not in", values, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("AUTHORIZED_DATE between", value1, value2, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("AUTHORIZED_DATE not between", value1, value2, "authorizedDate");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsIsNull() {
            addCriterion("DISCOUNT_FRCMS is null");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsIsNotNull() {
            addCriterion("DISCOUNT_FRCMS is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS =", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsNotEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS <>", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsGreaterThan(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS >", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS >=", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsLessThan(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS <", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DISCOUNT_FRCMS <=", value, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsIn(List<BigDecimal> values) {
            addCriterion("DISCOUNT_FRCMS in", values, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsNotIn(List<BigDecimal> values) {
            addCriterion("DISCOUNT_FRCMS not in", values, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_FRCMS between", value1, value2, "discountFrcms");
            return (Criteria) this;
        }

        public Criteria andDiscountFrcmsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DISCOUNT_FRCMS not between", value1, value2, "discountFrcms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}