package com.tgfc.som.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   訂單試算記錄檔
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_ORDER_COMPUTE
 */
public class TblOrderCompute implements Serializable {
    /**
     * Database Column Remarks:
     *   訂單
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   試算項目分類碼	(1: 商品小計, 2: 安裝小計, 3: 運送小計, 4: 會員卡折扣, 5: 直送費用小計, 6: 折價券折扣)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.COMPUTE_TYPE
     *
     * @mbg.generated
     */
    private String computeType;

    /**
     * Database Column Remarks:
     *   店別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.STORE_ID
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     * Database Column Remarks:
     *   總額
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.TOTAL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     * Database Column Remarks:
     *   折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.DISCOUNT
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     * Database Column Remarks:
     *   實際總額
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal actTotalPrice;

    /**
     * Database Column Remarks:
     *   應稅總額(總額折扣的部分需分攤至應/免稅)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_TX
     *
     * @mbg.generated
     */
    private BigDecimal actTotalPriceTx;

    /**
     * Database Column Remarks:
     *   免稅/零稅總額(零稅訂單總額全部掛此欄位；總額折扣的部分需分攤至應/免稅)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_NTX
     *
     * @mbg.generated
     */
    private BigDecimal actTotalPriceNtx;

    /**
     * Database Column Remarks:
     *   總額折扣授權者工號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_ID
     *
     * @mbg.generated
     */
    private String authorizedEmpId;

    /**
     * Database Column Remarks:
     *   總額折扣授權者姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_NAME
     *
     * @mbg.generated
     */
    private String authorizedEmpName;

    /**
     * Database Column Remarks:
     *   總額折扣原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.AUTHORIZED_REASON
     *
     * @mbg.generated
     */
    private String authorizedReason;

    /**
     * Database Column Remarks:
     *   新增、修改 UPDATE DATE
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * Database Column Remarks:
     *   總額折扣日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.AUTHORIZED_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime authorizedDate;

    /**
     * Database Column Remarks:
     *   加盟折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ORDER_COMPUTE.DISCOUNT_FRCMS
     *
     * @mbg.generated
     */
    private BigDecimal discountFrcms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.ORDER_ID
     *
     * @return the value of TBL_ORDER_COMPUTE.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.ORDER_ID
     *
     * @param orderId the value for TBL_ORDER_COMPUTE.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.COMPUTE_TYPE
     *
     * @return the value of TBL_ORDER_COMPUTE.COMPUTE_TYPE
     *
     * @mbg.generated
     */
    public String getComputeType() {
        return computeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.COMPUTE_TYPE
     *
     * @param computeType the value for TBL_ORDER_COMPUTE.COMPUTE_TYPE
     *
     * @mbg.generated
     */
    public void setComputeType(String computeType) {
        this.computeType = computeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.STORE_ID
     *
     * @return the value of TBL_ORDER_COMPUTE.STORE_ID
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.STORE_ID
     *
     * @param storeId the value for TBL_ORDER_COMPUTE.STORE_ID
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.TOTAL_PRICE
     *
     * @return the value of TBL_ORDER_COMPUTE.TOTAL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.TOTAL_PRICE
     *
     * @param totalPrice the value for TBL_ORDER_COMPUTE.TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.DISCOUNT
     *
     * @return the value of TBL_ORDER_COMPUTE.DISCOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.DISCOUNT
     *
     * @param discount the value for TBL_ORDER_COMPUTE.DISCOUNT
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE
     *
     * @return the value of TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getActTotalPrice() {
        return actTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE
     *
     * @param actTotalPrice the value for TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setActTotalPrice(BigDecimal actTotalPrice) {
        this.actTotalPrice = actTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_TX
     *
     * @return the value of TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_TX
     *
     * @mbg.generated
     */
    public BigDecimal getActTotalPriceTx() {
        return actTotalPriceTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_TX
     *
     * @param actTotalPriceTx the value for TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_TX
     *
     * @mbg.generated
     */
    public void setActTotalPriceTx(BigDecimal actTotalPriceTx) {
        this.actTotalPriceTx = actTotalPriceTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_NTX
     *
     * @return the value of TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_NTX
     *
     * @mbg.generated
     */
    public BigDecimal getActTotalPriceNtx() {
        return actTotalPriceNtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_NTX
     *
     * @param actTotalPriceNtx the value for TBL_ORDER_COMPUTE.ACT_TOTAL_PRICE_NTX
     *
     * @mbg.generated
     */
    public void setActTotalPriceNtx(BigDecimal actTotalPriceNtx) {
        this.actTotalPriceNtx = actTotalPriceNtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_ID
     *
     * @return the value of TBL_ORDER_COMPUTE.AUTHORIZED_EMP_ID
     *
     * @mbg.generated
     */
    public String getAuthorizedEmpId() {
        return authorizedEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_ID
     *
     * @param authorizedEmpId the value for TBL_ORDER_COMPUTE.AUTHORIZED_EMP_ID
     *
     * @mbg.generated
     */
    public void setAuthorizedEmpId(String authorizedEmpId) {
        this.authorizedEmpId = authorizedEmpId == null ? null : authorizedEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_NAME
     *
     * @return the value of TBL_ORDER_COMPUTE.AUTHORIZED_EMP_NAME
     *
     * @mbg.generated
     */
    public String getAuthorizedEmpName() {
        return authorizedEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_EMP_NAME
     *
     * @param authorizedEmpName the value for TBL_ORDER_COMPUTE.AUTHORIZED_EMP_NAME
     *
     * @mbg.generated
     */
    public void setAuthorizedEmpName(String authorizedEmpName) {
        this.authorizedEmpName = authorizedEmpName == null ? null : authorizedEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_REASON
     *
     * @return the value of TBL_ORDER_COMPUTE.AUTHORIZED_REASON
     *
     * @mbg.generated
     */
    public String getAuthorizedReason() {
        return authorizedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_REASON
     *
     * @param authorizedReason the value for TBL_ORDER_COMPUTE.AUTHORIZED_REASON
     *
     * @mbg.generated
     */
    public void setAuthorizedReason(String authorizedReason) {
        this.authorizedReason = authorizedReason == null ? null : authorizedReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.UPDATE_DATE
     *
     * @return the value of TBL_ORDER_COMPUTE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.UPDATE_DATE
     *
     * @param updateDate the value for TBL_ORDER_COMPUTE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_DATE
     *
     * @return the value of TBL_ORDER_COMPUTE.AUTHORIZED_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getAuthorizedDate() {
        return authorizedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.AUTHORIZED_DATE
     *
     * @param authorizedDate the value for TBL_ORDER_COMPUTE.AUTHORIZED_DATE
     *
     * @mbg.generated
     */
    public void setAuthorizedDate(LocalDateTime authorizedDate) {
        this.authorizedDate = authorizedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ORDER_COMPUTE.DISCOUNT_FRCMS
     *
     * @return the value of TBL_ORDER_COMPUTE.DISCOUNT_FRCMS
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountFrcms() {
        return discountFrcms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ORDER_COMPUTE.DISCOUNT_FRCMS
     *
     * @param discountFrcms the value for TBL_ORDER_COMPUTE.DISCOUNT_FRCMS
     *
     * @mbg.generated
     */
    public void setDiscountFrcms(BigDecimal discountFrcms) {
        this.discountFrcms = discountFrcms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", computeType=").append(computeType);
        sb.append(", storeId=").append(storeId);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", discount=").append(discount);
        sb.append(", actTotalPrice=").append(actTotalPrice);
        sb.append(", actTotalPriceTx=").append(actTotalPriceTx);
        sb.append(", actTotalPriceNtx=").append(actTotalPriceNtx);
        sb.append(", authorizedEmpId=").append(authorizedEmpId);
        sb.append(", authorizedEmpName=").append(authorizedEmpName);
        sb.append(", authorizedReason=").append(authorizedReason);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", authorizedDate=").append(authorizedDate);
        sb.append(", discountFrcms=").append(discountFrcms);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblOrderCompute other = (TblOrderCompute) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getComputeType() == null ? other.getComputeType() == null : this.getComputeType().equals(other.getComputeType()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getTotalPrice() == null ? other.getTotalPrice() == null : this.getTotalPrice().equals(other.getTotalPrice()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getActTotalPrice() == null ? other.getActTotalPrice() == null : this.getActTotalPrice().equals(other.getActTotalPrice()))
            && (this.getActTotalPriceTx() == null ? other.getActTotalPriceTx() == null : this.getActTotalPriceTx().equals(other.getActTotalPriceTx()))
            && (this.getActTotalPriceNtx() == null ? other.getActTotalPriceNtx() == null : this.getActTotalPriceNtx().equals(other.getActTotalPriceNtx()))
            && (this.getAuthorizedEmpId() == null ? other.getAuthorizedEmpId() == null : this.getAuthorizedEmpId().equals(other.getAuthorizedEmpId()))
            && (this.getAuthorizedEmpName() == null ? other.getAuthorizedEmpName() == null : this.getAuthorizedEmpName().equals(other.getAuthorizedEmpName()))
            && (this.getAuthorizedReason() == null ? other.getAuthorizedReason() == null : this.getAuthorizedReason().equals(other.getAuthorizedReason()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getAuthorizedDate() == null ? other.getAuthorizedDate() == null : this.getAuthorizedDate().equals(other.getAuthorizedDate()))
            && (this.getDiscountFrcms() == null ? other.getDiscountFrcms() == null : this.getDiscountFrcms().equals(other.getDiscountFrcms()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ORDER_COMPUTE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getComputeType() == null) ? 0 : getComputeType().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getTotalPrice() == null) ? 0 : getTotalPrice().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getActTotalPrice() == null) ? 0 : getActTotalPrice().hashCode());
        result = prime * result + ((getActTotalPriceTx() == null) ? 0 : getActTotalPriceTx().hashCode());
        result = prime * result + ((getActTotalPriceNtx() == null) ? 0 : getActTotalPriceNtx().hashCode());
        result = prime * result + ((getAuthorizedEmpId() == null) ? 0 : getAuthorizedEmpId().hashCode());
        result = prime * result + ((getAuthorizedEmpName() == null) ? 0 : getAuthorizedEmpName().hashCode());
        result = prime * result + ((getAuthorizedReason() == null) ? 0 : getAuthorizedReason().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getAuthorizedDate() == null) ? 0 : getAuthorizedDate().hashCode());
        result = prime * result + ((getDiscountFrcms() == null) ? 0 : getDiscountFrcms().hashCode());
        return result;
    }
}