package com.tgfc.som.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_SKU
 */
public class TblSku implements Serializable {
    /**
     * Database Column Remarks:
     *   商品編號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_NO
     *
     * @mbg.generated
     */
    private String skuNo;

    /**
     * Database Column Remarks:
     *   商品名稱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_NAME
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     * Database Column Remarks:
     *   條碼(商品主條碼)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.BARCODE
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     * Database Column Remarks:
     *   商品類型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_TYPE
     *
     * @mbg.generated
     */
    private String skuType;

    /**
     * Database Column Remarks:
     *   子部門
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SUB_DEPT_ID
     *
     * @mbg.generated
     */
    private String subDeptId;

    /**
     * Database Column Remarks:
     *   類別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.CLASS_ID
     *
     * @mbg.generated
     */
    private String classId;

    /**
     * Database Column Remarks:
     *   子類別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SUB_CLASS_ID
     *
     * @mbg.generated
     */
    private String subClassId;

    /**
     * Database Column Remarks:
     *   特別訂購商品(N-否；Y-是 (客製化商品))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SO_FLAG
     *
     * @mbg.generated
     */
    private String soFlag;

    /**
     * Database Column Remarks:
     *   主要供應商
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.VENDOR_ID
     *
     * @mbg.generated
     */
    private String vendorId;

    /**
     * Database Column Remarks:
     *   商品狀態(A: Active 正常, D: Discontinued  停止採購,但可銷售)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_STATUS
     *
     * @mbg.generated
     */
    private String skuStatus;

    /**
     * Database Column Remarks:
     *   稅別(0: 零稅, 1: 應稅, 2: 免稅)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.TAX_TYPE
     *
     * @mbg.generated
     */
    private String taxType;

    /**
     * Database Column Remarks:
     *   包裝入數(一包幾入)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.PACKS
     *
     * @mbg.generated
     */
    private BigDecimal packs;

    /**
     * Database Column Remarks:
     *   危險商品(N:否；Y:是)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.DANGER_FLAG
     *
     * @mbg.generated
     */
    private String dangerFlag;

    /**
     * Database Column Remarks:
     *   是否開放售價(N:不開放；Y:開放)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.OPEN_PRICE
     *
     * @mbg.generated
     */
    private String openPrice;

    /**
     * Database Column Remarks:
     *   免費宅配(N-否；Y-是 (免費運送)移至主檔)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.FREE_DELIVER
     *
     * @mbg.generated
     */
    private String freeDeliver;

    /**
     * Database Column Remarks:
     *   標準包裝量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.STD_PACK
     *
     * @mbg.generated
     */
    private BigDecimal stdPack;

    /**
     * Database Column Remarks:
     *   Inner Pack
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.INNER_PACK
     *
     * @mbg.generated
     */
    private BigDecimal innerPack;

    /**
     * Database Column Remarks:
     *   基本單位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_UNIT
     *
     * @mbg.generated
     */
    private String skuUnit;

    /**
     * Database Column Remarks:
     *   高
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.HEIGHT
     *
     * @mbg.generated
     */
    private BigDecimal height;

    /**
     * Database Column Remarks:
     *   寬
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.WIDTH
     *
     * @mbg.generated
     */
    private BigDecimal width;

    /**
     * Database Column Remarks:
     *   深
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.DEEPTH
     *
     * @mbg.generated
     */
    private BigDecimal deepth;

    /**
     * Database Column Remarks:
     *   長度單位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.DIMENSION
     *
     * @mbg.generated
     */
    private String dimension;

    /**
     * Database Column Remarks:
     *   重
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.WEIGHT
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     * Database Column Remarks:
     *   重量單位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.MAUND
     *
     * @mbg.generated
     */
    private String maund;

    /**
     * Database Column Remarks:
     *   最後修改日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.MODIFY_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     * Database Column Remarks:
     *   採購屬性 (XD: Cross Docking, DC: Stock Holding, VD: 供應商直送)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.DC_TYPE
     *
     * @mbg.generated
     */
    private String dcType;

    /**
     * Database Column Remarks:
     *   物料種類(00: single article、01: generic article、02: variant article、10: saleset (群組商品-賣母要扣子，母沒有庫存)、11: prepack、12: display (母子SKU-子母商品[一母對一子])、30: mc referenece article)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_CAT
     *
     * @mbg.generated
     */
    private String skuCat;

    /**
     * Database Column Remarks:
     *   1.HISU專屬欄位
2.對應TBL_WEBQUO_HISU_MC的第三層MC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.HISU_MC
     *
     * @mbg.generated
     */
    private String hisuMc;

    /**
     * Database Column Remarks:
     *   商品群組
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SKU_MC
     *
     * @mbg.generated
     */
    private String skuMc;

    /**
     * Database Column Remarks:
     *   廠牌，HISU專屬欄位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.BRAND
     *
     * @mbg.generated
     */
    private String brand;

    /**
     * Database Column Remarks:
     *   風格型號，1.HISU專屬欄位
2.對應WEBQUO_STYLE
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.STYLE_NO
     *
     * @mbg.generated
     */
    private String styleNo;

    /**
     * Database Column Remarks:
     *   "桶身類型
1.HISU專屬欄位
2.對應WEBQUO_MISC_CODE的CODE_TYPE='BARREL_TYPE'
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.BARREL_TYPE
     *
     * @mbg.generated
     */
    private String barrelType;

    /**
     * Database Column Remarks:
     *   把手類型，1.HISU專屬欄位
2.對應WEBQUO_HANDLE_TYPE
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.HANDLE_TYPE
     *
     * @mbg.generated
     */
    private String handleType;

    /**
     * Database Column Remarks:
     *   門板尺寸級距，
1.HISU專屬欄位
2.對應WEBQUO_COMBINED_CODE（USE_TYPE=2）
3.此為設定把手適用的門板尺寸級距
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.HANDLE_SIZE_CODE
     *
     * @mbg.generated
     */
    private String handleSizeCode;

    /**
     * Database Column Remarks:
     *   自訂組合代碼，
1.HISU專屬欄位
2.對應WEBQUO_COMBINED_CODE（USE_TYPE=1）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.COMBINED_CODE
     *
     * @mbg.generated
     */
    private String combinedCode;

    /**
     * Database Column Remarks:
     *   報價單生效日，1.HISU專屬欄位
2.只儲存日期，例如2015-10-31 hh:mm:ss.fff
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.QUO_VALID_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime quoValidDate;

    /**
     * Database Column Remarks:
     *   報價單停用日，1.HISU專屬欄位
2.只儲存日期，例如2015/10/31 hh:mm:ss.fff
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.QUO_INVALID_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime quoInvalidDate;

    /**
     * Database Column Remarks:
     *   圖片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.PHOTO
     *
     * @mbg.generated
     */
    private String photo;

    /**
     * Database Column Remarks:
     *   修改人帳號，SPL人員
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SPL_MODIFIER
     *
     * @mbg.generated
     */
    private String splModifier;

    /**
     * Database Column Remarks:
     *   修改日期時間，SPL異動時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SPL_MODIFY_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime splModifyTime;

    /**
     * Database Column Remarks:
     *   特殊規格原因代碼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SKU.SO_REASON
     *
     * @mbg.generated
     */
    private String soReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_NO
     *
     * @return the value of TBL_SKU.SKU_NO
     *
     * @mbg.generated
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_NO
     *
     * @param skuNo the value for TBL_SKU.SKU_NO
     *
     * @mbg.generated
     */
    public void setSkuNo(String skuNo) {
        this.skuNo = skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_NAME
     *
     * @return the value of TBL_SKU.SKU_NAME
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_NAME
     *
     * @param skuName the value for TBL_SKU.SKU_NAME
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.BARCODE
     *
     * @return the value of TBL_SKU.BARCODE
     *
     * @mbg.generated
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.BARCODE
     *
     * @param barcode the value for TBL_SKU.BARCODE
     *
     * @mbg.generated
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_TYPE
     *
     * @return the value of TBL_SKU.SKU_TYPE
     *
     * @mbg.generated
     */
    public String getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_TYPE
     *
     * @param skuType the value for TBL_SKU.SKU_TYPE
     *
     * @mbg.generated
     */
    public void setSkuType(String skuType) {
        this.skuType = skuType == null ? null : skuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SUB_DEPT_ID
     *
     * @return the value of TBL_SKU.SUB_DEPT_ID
     *
     * @mbg.generated
     */
    public String getSubDeptId() {
        return subDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SUB_DEPT_ID
     *
     * @param subDeptId the value for TBL_SKU.SUB_DEPT_ID
     *
     * @mbg.generated
     */
    public void setSubDeptId(String subDeptId) {
        this.subDeptId = subDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.CLASS_ID
     *
     * @return the value of TBL_SKU.CLASS_ID
     *
     * @mbg.generated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.CLASS_ID
     *
     * @param classId the value for TBL_SKU.CLASS_ID
     *
     * @mbg.generated
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SUB_CLASS_ID
     *
     * @return the value of TBL_SKU.SUB_CLASS_ID
     *
     * @mbg.generated
     */
    public String getSubClassId() {
        return subClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SUB_CLASS_ID
     *
     * @param subClassId the value for TBL_SKU.SUB_CLASS_ID
     *
     * @mbg.generated
     */
    public void setSubClassId(String subClassId) {
        this.subClassId = subClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SO_FLAG
     *
     * @return the value of TBL_SKU.SO_FLAG
     *
     * @mbg.generated
     */
    public String getSoFlag() {
        return soFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SO_FLAG
     *
     * @param soFlag the value for TBL_SKU.SO_FLAG
     *
     * @mbg.generated
     */
    public void setSoFlag(String soFlag) {
        this.soFlag = soFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.VENDOR_ID
     *
     * @return the value of TBL_SKU.VENDOR_ID
     *
     * @mbg.generated
     */
    public String getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.VENDOR_ID
     *
     * @param vendorId the value for TBL_SKU.VENDOR_ID
     *
     * @mbg.generated
     */
    public void setVendorId(String vendorId) {
        this.vendorId = vendorId == null ? null : vendorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_STATUS
     *
     * @return the value of TBL_SKU.SKU_STATUS
     *
     * @mbg.generated
     */
    public String getSkuStatus() {
        return skuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_STATUS
     *
     * @param skuStatus the value for TBL_SKU.SKU_STATUS
     *
     * @mbg.generated
     */
    public void setSkuStatus(String skuStatus) {
        this.skuStatus = skuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.TAX_TYPE
     *
     * @return the value of TBL_SKU.TAX_TYPE
     *
     * @mbg.generated
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.TAX_TYPE
     *
     * @param taxType the value for TBL_SKU.TAX_TYPE
     *
     * @mbg.generated
     */
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.PACKS
     *
     * @return the value of TBL_SKU.PACKS
     *
     * @mbg.generated
     */
    public BigDecimal getPacks() {
        return packs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.PACKS
     *
     * @param packs the value for TBL_SKU.PACKS
     *
     * @mbg.generated
     */
    public void setPacks(BigDecimal packs) {
        this.packs = packs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.DANGER_FLAG
     *
     * @return the value of TBL_SKU.DANGER_FLAG
     *
     * @mbg.generated
     */
    public String getDangerFlag() {
        return dangerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.DANGER_FLAG
     *
     * @param dangerFlag the value for TBL_SKU.DANGER_FLAG
     *
     * @mbg.generated
     */
    public void setDangerFlag(String dangerFlag) {
        this.dangerFlag = dangerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.OPEN_PRICE
     *
     * @return the value of TBL_SKU.OPEN_PRICE
     *
     * @mbg.generated
     */
    public String getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.OPEN_PRICE
     *
     * @param openPrice the value for TBL_SKU.OPEN_PRICE
     *
     * @mbg.generated
     */
    public void setOpenPrice(String openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.FREE_DELIVER
     *
     * @return the value of TBL_SKU.FREE_DELIVER
     *
     * @mbg.generated
     */
    public String getFreeDeliver() {
        return freeDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.FREE_DELIVER
     *
     * @param freeDeliver the value for TBL_SKU.FREE_DELIVER
     *
     * @mbg.generated
     */
    public void setFreeDeliver(String freeDeliver) {
        this.freeDeliver = freeDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.STD_PACK
     *
     * @return the value of TBL_SKU.STD_PACK
     *
     * @mbg.generated
     */
    public BigDecimal getStdPack() {
        return stdPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.STD_PACK
     *
     * @param stdPack the value for TBL_SKU.STD_PACK
     *
     * @mbg.generated
     */
    public void setStdPack(BigDecimal stdPack) {
        this.stdPack = stdPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.INNER_PACK
     *
     * @return the value of TBL_SKU.INNER_PACK
     *
     * @mbg.generated
     */
    public BigDecimal getInnerPack() {
        return innerPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.INNER_PACK
     *
     * @param innerPack the value for TBL_SKU.INNER_PACK
     *
     * @mbg.generated
     */
    public void setInnerPack(BigDecimal innerPack) {
        this.innerPack = innerPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_UNIT
     *
     * @return the value of TBL_SKU.SKU_UNIT
     *
     * @mbg.generated
     */
    public String getSkuUnit() {
        return skuUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_UNIT
     *
     * @param skuUnit the value for TBL_SKU.SKU_UNIT
     *
     * @mbg.generated
     */
    public void setSkuUnit(String skuUnit) {
        this.skuUnit = skuUnit == null ? null : skuUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.HEIGHT
     *
     * @return the value of TBL_SKU.HEIGHT
     *
     * @mbg.generated
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.HEIGHT
     *
     * @param height the value for TBL_SKU.HEIGHT
     *
     * @mbg.generated
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.WIDTH
     *
     * @return the value of TBL_SKU.WIDTH
     *
     * @mbg.generated
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.WIDTH
     *
     * @param width the value for TBL_SKU.WIDTH
     *
     * @mbg.generated
     */
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.DEEPTH
     *
     * @return the value of TBL_SKU.DEEPTH
     *
     * @mbg.generated
     */
    public BigDecimal getDeepth() {
        return deepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.DEEPTH
     *
     * @param deepth the value for TBL_SKU.DEEPTH
     *
     * @mbg.generated
     */
    public void setDeepth(BigDecimal deepth) {
        this.deepth = deepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.DIMENSION
     *
     * @return the value of TBL_SKU.DIMENSION
     *
     * @mbg.generated
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.DIMENSION
     *
     * @param dimension the value for TBL_SKU.DIMENSION
     *
     * @mbg.generated
     */
    public void setDimension(String dimension) {
        this.dimension = dimension == null ? null : dimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.WEIGHT
     *
     * @return the value of TBL_SKU.WEIGHT
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.WEIGHT
     *
     * @param weight the value for TBL_SKU.WEIGHT
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.MAUND
     *
     * @return the value of TBL_SKU.MAUND
     *
     * @mbg.generated
     */
    public String getMaund() {
        return maund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.MAUND
     *
     * @param maund the value for TBL_SKU.MAUND
     *
     * @mbg.generated
     */
    public void setMaund(String maund) {
        this.maund = maund == null ? null : maund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.MODIFY_TIME
     *
     * @return the value of TBL_SKU.MODIFY_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.MODIFY_TIME
     *
     * @param modifyTime the value for TBL_SKU.MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.DC_TYPE
     *
     * @return the value of TBL_SKU.DC_TYPE
     *
     * @mbg.generated
     */
    public String getDcType() {
        return dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.DC_TYPE
     *
     * @param dcType the value for TBL_SKU.DC_TYPE
     *
     * @mbg.generated
     */
    public void setDcType(String dcType) {
        this.dcType = dcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_CAT
     *
     * @return the value of TBL_SKU.SKU_CAT
     *
     * @mbg.generated
     */
    public String getSkuCat() {
        return skuCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_CAT
     *
     * @param skuCat the value for TBL_SKU.SKU_CAT
     *
     * @mbg.generated
     */
    public void setSkuCat(String skuCat) {
        this.skuCat = skuCat == null ? null : skuCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.HISU_MC
     *
     * @return the value of TBL_SKU.HISU_MC
     *
     * @mbg.generated
     */
    public String getHisuMc() {
        return hisuMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.HISU_MC
     *
     * @param hisuMc the value for TBL_SKU.HISU_MC
     *
     * @mbg.generated
     */
    public void setHisuMc(String hisuMc) {
        this.hisuMc = hisuMc == null ? null : hisuMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SKU_MC
     *
     * @return the value of TBL_SKU.SKU_MC
     *
     * @mbg.generated
     */
    public String getSkuMc() {
        return skuMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SKU_MC
     *
     * @param skuMc the value for TBL_SKU.SKU_MC
     *
     * @mbg.generated
     */
    public void setSkuMc(String skuMc) {
        this.skuMc = skuMc == null ? null : skuMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.BRAND
     *
     * @return the value of TBL_SKU.BRAND
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.BRAND
     *
     * @param brand the value for TBL_SKU.BRAND
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.STYLE_NO
     *
     * @return the value of TBL_SKU.STYLE_NO
     *
     * @mbg.generated
     */
    public String getStyleNo() {
        return styleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.STYLE_NO
     *
     * @param styleNo the value for TBL_SKU.STYLE_NO
     *
     * @mbg.generated
     */
    public void setStyleNo(String styleNo) {
        this.styleNo = styleNo == null ? null : styleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.BARREL_TYPE
     *
     * @return the value of TBL_SKU.BARREL_TYPE
     *
     * @mbg.generated
     */
    public String getBarrelType() {
        return barrelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.BARREL_TYPE
     *
     * @param barrelType the value for TBL_SKU.BARREL_TYPE
     *
     * @mbg.generated
     */
    public void setBarrelType(String barrelType) {
        this.barrelType = barrelType == null ? null : barrelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.HANDLE_TYPE
     *
     * @return the value of TBL_SKU.HANDLE_TYPE
     *
     * @mbg.generated
     */
    public String getHandleType() {
        return handleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.HANDLE_TYPE
     *
     * @param handleType the value for TBL_SKU.HANDLE_TYPE
     *
     * @mbg.generated
     */
    public void setHandleType(String handleType) {
        this.handleType = handleType == null ? null : handleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.HANDLE_SIZE_CODE
     *
     * @return the value of TBL_SKU.HANDLE_SIZE_CODE
     *
     * @mbg.generated
     */
    public String getHandleSizeCode() {
        return handleSizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.HANDLE_SIZE_CODE
     *
     * @param handleSizeCode the value for TBL_SKU.HANDLE_SIZE_CODE
     *
     * @mbg.generated
     */
    public void setHandleSizeCode(String handleSizeCode) {
        this.handleSizeCode = handleSizeCode == null ? null : handleSizeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.COMBINED_CODE
     *
     * @return the value of TBL_SKU.COMBINED_CODE
     *
     * @mbg.generated
     */
    public String getCombinedCode() {
        return combinedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.COMBINED_CODE
     *
     * @param combinedCode the value for TBL_SKU.COMBINED_CODE
     *
     * @mbg.generated
     */
    public void setCombinedCode(String combinedCode) {
        this.combinedCode = combinedCode == null ? null : combinedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.QUO_VALID_DATE
     *
     * @return the value of TBL_SKU.QUO_VALID_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getQuoValidDate() {
        return quoValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.QUO_VALID_DATE
     *
     * @param quoValidDate the value for TBL_SKU.QUO_VALID_DATE
     *
     * @mbg.generated
     */
    public void setQuoValidDate(LocalDateTime quoValidDate) {
        this.quoValidDate = quoValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.QUO_INVALID_DATE
     *
     * @return the value of TBL_SKU.QUO_INVALID_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getQuoInvalidDate() {
        return quoInvalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.QUO_INVALID_DATE
     *
     * @param quoInvalidDate the value for TBL_SKU.QUO_INVALID_DATE
     *
     * @mbg.generated
     */
    public void setQuoInvalidDate(LocalDateTime quoInvalidDate) {
        this.quoInvalidDate = quoInvalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.PHOTO
     *
     * @return the value of TBL_SKU.PHOTO
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.PHOTO
     *
     * @param photo the value for TBL_SKU.PHOTO
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SPL_MODIFIER
     *
     * @return the value of TBL_SKU.SPL_MODIFIER
     *
     * @mbg.generated
     */
    public String getSplModifier() {
        return splModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SPL_MODIFIER
     *
     * @param splModifier the value for TBL_SKU.SPL_MODIFIER
     *
     * @mbg.generated
     */
    public void setSplModifier(String splModifier) {
        this.splModifier = splModifier == null ? null : splModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SPL_MODIFY_TIME
     *
     * @return the value of TBL_SKU.SPL_MODIFY_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getSplModifyTime() {
        return splModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SPL_MODIFY_TIME
     *
     * @param splModifyTime the value for TBL_SKU.SPL_MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setSplModifyTime(LocalDateTime splModifyTime) {
        this.splModifyTime = splModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SKU.SO_REASON
     *
     * @return the value of TBL_SKU.SO_REASON
     *
     * @mbg.generated
     */
    public String getSoReason() {
        return soReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SKU.SO_REASON
     *
     * @param soReason the value for TBL_SKU.SO_REASON
     *
     * @mbg.generated
     */
    public void setSoReason(String soReason) {
        this.soReason = soReason == null ? null : soReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", skuNo=").append(skuNo);
        sb.append(", skuName=").append(skuName);
        sb.append(", barcode=").append(barcode);
        sb.append(", skuType=").append(skuType);
        sb.append(", subDeptId=").append(subDeptId);
        sb.append(", classId=").append(classId);
        sb.append(", subClassId=").append(subClassId);
        sb.append(", soFlag=").append(soFlag);
        sb.append(", vendorId=").append(vendorId);
        sb.append(", skuStatus=").append(skuStatus);
        sb.append(", taxType=").append(taxType);
        sb.append(", packs=").append(packs);
        sb.append(", dangerFlag=").append(dangerFlag);
        sb.append(", openPrice=").append(openPrice);
        sb.append(", freeDeliver=").append(freeDeliver);
        sb.append(", stdPack=").append(stdPack);
        sb.append(", innerPack=").append(innerPack);
        sb.append(", skuUnit=").append(skuUnit);
        sb.append(", height=").append(height);
        sb.append(", width=").append(width);
        sb.append(", deepth=").append(deepth);
        sb.append(", dimension=").append(dimension);
        sb.append(", weight=").append(weight);
        sb.append(", maund=").append(maund);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dcType=").append(dcType);
        sb.append(", skuCat=").append(skuCat);
        sb.append(", hisuMc=").append(hisuMc);
        sb.append(", skuMc=").append(skuMc);
        sb.append(", brand=").append(brand);
        sb.append(", styleNo=").append(styleNo);
        sb.append(", barrelType=").append(barrelType);
        sb.append(", handleType=").append(handleType);
        sb.append(", handleSizeCode=").append(handleSizeCode);
        sb.append(", combinedCode=").append(combinedCode);
        sb.append(", quoValidDate=").append(quoValidDate);
        sb.append(", quoInvalidDate=").append(quoInvalidDate);
        sb.append(", photo=").append(photo);
        sb.append(", splModifier=").append(splModifier);
        sb.append(", splModifyTime=").append(splModifyTime);
        sb.append(", soReason=").append(soReason);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblSku other = (TblSku) that;
        return (this.getSkuNo() == null ? other.getSkuNo() == null : this.getSkuNo().equals(other.getSkuNo()))
            && (this.getSkuName() == null ? other.getSkuName() == null : this.getSkuName().equals(other.getSkuName()))
            && (this.getBarcode() == null ? other.getBarcode() == null : this.getBarcode().equals(other.getBarcode()))
            && (this.getSkuType() == null ? other.getSkuType() == null : this.getSkuType().equals(other.getSkuType()))
            && (this.getSubDeptId() == null ? other.getSubDeptId() == null : this.getSubDeptId().equals(other.getSubDeptId()))
            && (this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()))
            && (this.getSubClassId() == null ? other.getSubClassId() == null : this.getSubClassId().equals(other.getSubClassId()))
            && (this.getSoFlag() == null ? other.getSoFlag() == null : this.getSoFlag().equals(other.getSoFlag()))
            && (this.getVendorId() == null ? other.getVendorId() == null : this.getVendorId().equals(other.getVendorId()))
            && (this.getSkuStatus() == null ? other.getSkuStatus() == null : this.getSkuStatus().equals(other.getSkuStatus()))
            && (this.getTaxType() == null ? other.getTaxType() == null : this.getTaxType().equals(other.getTaxType()))
            && (this.getPacks() == null ? other.getPacks() == null : this.getPacks().equals(other.getPacks()))
            && (this.getDangerFlag() == null ? other.getDangerFlag() == null : this.getDangerFlag().equals(other.getDangerFlag()))
            && (this.getOpenPrice() == null ? other.getOpenPrice() == null : this.getOpenPrice().equals(other.getOpenPrice()))
            && (this.getFreeDeliver() == null ? other.getFreeDeliver() == null : this.getFreeDeliver().equals(other.getFreeDeliver()))
            && (this.getStdPack() == null ? other.getStdPack() == null : this.getStdPack().equals(other.getStdPack()))
            && (this.getInnerPack() == null ? other.getInnerPack() == null : this.getInnerPack().equals(other.getInnerPack()))
            && (this.getSkuUnit() == null ? other.getSkuUnit() == null : this.getSkuUnit().equals(other.getSkuUnit()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()))
            && (this.getWidth() == null ? other.getWidth() == null : this.getWidth().equals(other.getWidth()))
            && (this.getDeepth() == null ? other.getDeepth() == null : this.getDeepth().equals(other.getDeepth()))
            && (this.getDimension() == null ? other.getDimension() == null : this.getDimension().equals(other.getDimension()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getMaund() == null ? other.getMaund() == null : this.getMaund().equals(other.getMaund()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDcType() == null ? other.getDcType() == null : this.getDcType().equals(other.getDcType()))
            && (this.getSkuCat() == null ? other.getSkuCat() == null : this.getSkuCat().equals(other.getSkuCat()))
            && (this.getHisuMc() == null ? other.getHisuMc() == null : this.getHisuMc().equals(other.getHisuMc()))
            && (this.getSkuMc() == null ? other.getSkuMc() == null : this.getSkuMc().equals(other.getSkuMc()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getStyleNo() == null ? other.getStyleNo() == null : this.getStyleNo().equals(other.getStyleNo()))
            && (this.getBarrelType() == null ? other.getBarrelType() == null : this.getBarrelType().equals(other.getBarrelType()))
            && (this.getHandleType() == null ? other.getHandleType() == null : this.getHandleType().equals(other.getHandleType()))
            && (this.getHandleSizeCode() == null ? other.getHandleSizeCode() == null : this.getHandleSizeCode().equals(other.getHandleSizeCode()))
            && (this.getCombinedCode() == null ? other.getCombinedCode() == null : this.getCombinedCode().equals(other.getCombinedCode()))
            && (this.getQuoValidDate() == null ? other.getQuoValidDate() == null : this.getQuoValidDate().equals(other.getQuoValidDate()))
            && (this.getQuoInvalidDate() == null ? other.getQuoInvalidDate() == null : this.getQuoInvalidDate().equals(other.getQuoInvalidDate()))
            && (this.getPhoto() == null ? other.getPhoto() == null : this.getPhoto().equals(other.getPhoto()))
            && (this.getSplModifier() == null ? other.getSplModifier() == null : this.getSplModifier().equals(other.getSplModifier()))
            && (this.getSplModifyTime() == null ? other.getSplModifyTime() == null : this.getSplModifyTime().equals(other.getSplModifyTime()))
            && (this.getSoReason() == null ? other.getSoReason() == null : this.getSoReason().equals(other.getSoReason()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSkuNo() == null) ? 0 : getSkuNo().hashCode());
        result = prime * result + ((getSkuName() == null) ? 0 : getSkuName().hashCode());
        result = prime * result + ((getBarcode() == null) ? 0 : getBarcode().hashCode());
        result = prime * result + ((getSkuType() == null) ? 0 : getSkuType().hashCode());
        result = prime * result + ((getSubDeptId() == null) ? 0 : getSubDeptId().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        result = prime * result + ((getSubClassId() == null) ? 0 : getSubClassId().hashCode());
        result = prime * result + ((getSoFlag() == null) ? 0 : getSoFlag().hashCode());
        result = prime * result + ((getVendorId() == null) ? 0 : getVendorId().hashCode());
        result = prime * result + ((getSkuStatus() == null) ? 0 : getSkuStatus().hashCode());
        result = prime * result + ((getTaxType() == null) ? 0 : getTaxType().hashCode());
        result = prime * result + ((getPacks() == null) ? 0 : getPacks().hashCode());
        result = prime * result + ((getDangerFlag() == null) ? 0 : getDangerFlag().hashCode());
        result = prime * result + ((getOpenPrice() == null) ? 0 : getOpenPrice().hashCode());
        result = prime * result + ((getFreeDeliver() == null) ? 0 : getFreeDeliver().hashCode());
        result = prime * result + ((getStdPack() == null) ? 0 : getStdPack().hashCode());
        result = prime * result + ((getInnerPack() == null) ? 0 : getInnerPack().hashCode());
        result = prime * result + ((getSkuUnit() == null) ? 0 : getSkuUnit().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        result = prime * result + ((getWidth() == null) ? 0 : getWidth().hashCode());
        result = prime * result + ((getDeepth() == null) ? 0 : getDeepth().hashCode());
        result = prime * result + ((getDimension() == null) ? 0 : getDimension().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getMaund() == null) ? 0 : getMaund().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDcType() == null) ? 0 : getDcType().hashCode());
        result = prime * result + ((getSkuCat() == null) ? 0 : getSkuCat().hashCode());
        result = prime * result + ((getHisuMc() == null) ? 0 : getHisuMc().hashCode());
        result = prime * result + ((getSkuMc() == null) ? 0 : getSkuMc().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getStyleNo() == null) ? 0 : getStyleNo().hashCode());
        result = prime * result + ((getBarrelType() == null) ? 0 : getBarrelType().hashCode());
        result = prime * result + ((getHandleType() == null) ? 0 : getHandleType().hashCode());
        result = prime * result + ((getHandleSizeCode() == null) ? 0 : getHandleSizeCode().hashCode());
        result = prime * result + ((getCombinedCode() == null) ? 0 : getCombinedCode().hashCode());
        result = prime * result + ((getQuoValidDate() == null) ? 0 : getQuoValidDate().hashCode());
        result = prime * result + ((getQuoInvalidDate() == null) ? 0 : getQuoInvalidDate().hashCode());
        result = prime * result + ((getPhoto() == null) ? 0 : getPhoto().hashCode());
        result = prime * result + ((getSplModifier() == null) ? 0 : getSplModifier().hashCode());
        result = prime * result + ((getSplModifyTime() == null) ? 0 : getSplModifyTime().hashCode());
        result = prime * result + ((getSoReason() == null) ? 0 : getSoReason().hashCode());
        return result;
    }
}