package com.tgfc.som.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TblSkuStoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public TblSkuStoreExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("STORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("STORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(String value) {
            addCriterion("STORE_ID =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(String value) {
            addCriterion("STORE_ID <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(String value) {
            addCriterion("STORE_ID >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_ID >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(String value) {
            addCriterion("STORE_ID <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(String value) {
            addCriterion("STORE_ID <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLike(String value) {
            addCriterion("STORE_ID like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotLike(String value) {
            addCriterion("STORE_ID not like", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<String> values) {
            addCriterion("STORE_ID in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<String> values) {
            addCriterion("STORE_ID not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(String value1, String value2) {
            addCriterion("STORE_ID between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(String value1, String value2) {
            addCriterion("STORE_ID not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andSkuNoIsNull() {
            addCriterion("SKU_NO is null");
            return (Criteria) this;
        }

        public Criteria andSkuNoIsNotNull() {
            addCriterion("SKU_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNoEqualTo(String value) {
            addCriterion("SKU_NO =", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoNotEqualTo(String value) {
            addCriterion("SKU_NO <>", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoGreaterThan(String value) {
            addCriterion("SKU_NO >", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_NO >=", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoLessThan(String value) {
            addCriterion("SKU_NO <", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoLessThanOrEqualTo(String value) {
            addCriterion("SKU_NO <=", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoLike(String value) {
            addCriterion("SKU_NO like", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoNotLike(String value) {
            addCriterion("SKU_NO not like", value, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoIn(List<String> values) {
            addCriterion("SKU_NO in", values, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoNotIn(List<String> values) {
            addCriterion("SKU_NO not in", values, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoBetween(String value1, String value2) {
            addCriterion("SKU_NO between", value1, value2, "skuNo");
            return (Criteria) this;
        }

        public Criteria andSkuNoNotBetween(String value1, String value2) {
            addCriterion("SKU_NO not between", value1, value2, "skuNo");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("CHANNEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("CHANNEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(String value) {
            addCriterion("CHANNEL_ID =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ID <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(String value) {
            addCriterion("CHANNEL_ID >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(String value) {
            addCriterion("CHANNEL_ID <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ID <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLike(String value) {
            addCriterion("CHANNEL_ID like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotLike(String value) {
            addCriterion("CHANNEL_ID not like", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<String> values) {
            addCriterion("CHANNEL_ID in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ID not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ID not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNull() {
            addCriterion("MARKET_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIsNotNull() {
            addCriterion("MARKET_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketPriceEqualTo(BigDecimal value) {
            addCriterion("MARKET_PRICE =", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotEqualTo(BigDecimal value) {
            addCriterion("MARKET_PRICE <>", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThan(BigDecimal value) {
            addCriterion("MARKET_PRICE >", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKET_PRICE >=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThan(BigDecimal value) {
            addCriterion("MARKET_PRICE <", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MARKET_PRICE <=", value, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceIn(List<BigDecimal> values) {
            addCriterion("MARKET_PRICE in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotIn(List<BigDecimal> values) {
            addCriterion("MARKET_PRICE not in", values, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKET_PRICE between", value1, value2, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andMarketPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MARKET_PRICE not between", value1, value2, "marketPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceIsNull() {
            addCriterion("REGULAR_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andRegularPriceIsNotNull() {
            addCriterion("REGULAR_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andRegularPriceEqualTo(BigDecimal value) {
            addCriterion("REGULAR_PRICE =", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceNotEqualTo(BigDecimal value) {
            addCriterion("REGULAR_PRICE <>", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceGreaterThan(BigDecimal value) {
            addCriterion("REGULAR_PRICE >", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REGULAR_PRICE >=", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceLessThan(BigDecimal value) {
            addCriterion("REGULAR_PRICE <", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REGULAR_PRICE <=", value, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceIn(List<BigDecimal> values) {
            addCriterion("REGULAR_PRICE in", values, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceNotIn(List<BigDecimal> values) {
            addCriterion("REGULAR_PRICE not in", values, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGULAR_PRICE between", value1, value2, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andRegularPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REGULAR_PRICE not between", value1, value2, "regularPrice");
            return (Criteria) this;
        }

        public Criteria andPosAmtIsNull() {
            addCriterion("POS_AMT is null");
            return (Criteria) this;
        }

        public Criteria andPosAmtIsNotNull() {
            addCriterion("POS_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andPosAmtEqualTo(BigDecimal value) {
            addCriterion("POS_AMT =", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtNotEqualTo(BigDecimal value) {
            addCriterion("POS_AMT <>", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtGreaterThan(BigDecimal value) {
            addCriterion("POS_AMT >", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("POS_AMT >=", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtLessThan(BigDecimal value) {
            addCriterion("POS_AMT <", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("POS_AMT <=", value, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtIn(List<BigDecimal> values) {
            addCriterion("POS_AMT in", values, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtNotIn(List<BigDecimal> values) {
            addCriterion("POS_AMT not in", values, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POS_AMT between", value1, value2, "posAmt");
            return (Criteria) this;
        }

        public Criteria andPosAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POS_AMT not between", value1, value2, "posAmt");
            return (Criteria) this;
        }

        public Criteria andAvgCostIsNull() {
            addCriterion("AVG_COST is null");
            return (Criteria) this;
        }

        public Criteria andAvgCostIsNotNull() {
            addCriterion("AVG_COST is not null");
            return (Criteria) this;
        }

        public Criteria andAvgCostEqualTo(BigDecimal value) {
            addCriterion("AVG_COST =", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotEqualTo(BigDecimal value) {
            addCriterion("AVG_COST <>", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostGreaterThan(BigDecimal value) {
            addCriterion("AVG_COST >", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVG_COST >=", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostLessThan(BigDecimal value) {
            addCriterion("AVG_COST <", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVG_COST <=", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostIn(List<BigDecimal> values) {
            addCriterion("AVG_COST in", values, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotIn(List<BigDecimal> values) {
            addCriterion("AVG_COST not in", values, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVG_COST between", value1, value2, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVG_COST not between", value1, value2, "avgCost");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIsNull() {
            addCriterion("SKU_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIsNotNull() {
            addCriterion("SKU_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSkuStatusEqualTo(String value) {
            addCriterion("SKU_STATUS =", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotEqualTo(String value) {
            addCriterion("SKU_STATUS <>", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusGreaterThan(String value) {
            addCriterion("SKU_STATUS >", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_STATUS >=", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusLessThan(String value) {
            addCriterion("SKU_STATUS <", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusLessThanOrEqualTo(String value) {
            addCriterion("SKU_STATUS <=", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusLike(String value) {
            addCriterion("SKU_STATUS like", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotLike(String value) {
            addCriterion("SKU_STATUS not like", value, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusIn(List<String> values) {
            addCriterion("SKU_STATUS in", values, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotIn(List<String> values) {
            addCriterion("SKU_STATUS not in", values, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusBetween(String value1, String value2) {
            addCriterion("SKU_STATUS between", value1, value2, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andSkuStatusNotBetween(String value1, String value2) {
            addCriterion("SKU_STATUS not between", value1, value2, "skuStatus");
            return (Criteria) this;
        }

        public Criteria andAllowReturnIsNull() {
            addCriterion("ALLOW_RETURN is null");
            return (Criteria) this;
        }

        public Criteria andAllowReturnIsNotNull() {
            addCriterion("ALLOW_RETURN is not null");
            return (Criteria) this;
        }

        public Criteria andAllowReturnEqualTo(String value) {
            addCriterion("ALLOW_RETURN =", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnNotEqualTo(String value) {
            addCriterion("ALLOW_RETURN <>", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnGreaterThan(String value) {
            addCriterion("ALLOW_RETURN >", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnGreaterThanOrEqualTo(String value) {
            addCriterion("ALLOW_RETURN >=", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnLessThan(String value) {
            addCriterion("ALLOW_RETURN <", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnLessThanOrEqualTo(String value) {
            addCriterion("ALLOW_RETURN <=", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnLike(String value) {
            addCriterion("ALLOW_RETURN like", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnNotLike(String value) {
            addCriterion("ALLOW_RETURN not like", value, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnIn(List<String> values) {
            addCriterion("ALLOW_RETURN in", values, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnNotIn(List<String> values) {
            addCriterion("ALLOW_RETURN not in", values, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnBetween(String value1, String value2) {
            addCriterion("ALLOW_RETURN between", value1, value2, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andAllowReturnNotBetween(String value1, String value2) {
            addCriterion("ALLOW_RETURN not between", value1, value2, "allowReturn");
            return (Criteria) this;
        }

        public Criteria andHoldOrderIsNull() {
            addCriterion("HOLD_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andHoldOrderIsNotNull() {
            addCriterion("HOLD_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andHoldOrderEqualTo(String value) {
            addCriterion("HOLD_ORDER =", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderNotEqualTo(String value) {
            addCriterion("HOLD_ORDER <>", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderGreaterThan(String value) {
            addCriterion("HOLD_ORDER >", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderGreaterThanOrEqualTo(String value) {
            addCriterion("HOLD_ORDER >=", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderLessThan(String value) {
            addCriterion("HOLD_ORDER <", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderLessThanOrEqualTo(String value) {
            addCriterion("HOLD_ORDER <=", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderLike(String value) {
            addCriterion("HOLD_ORDER like", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderNotLike(String value) {
            addCriterion("HOLD_ORDER not like", value, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderIn(List<String> values) {
            addCriterion("HOLD_ORDER in", values, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderNotIn(List<String> values) {
            addCriterion("HOLD_ORDER not in", values, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderBetween(String value1, String value2) {
            addCriterion("HOLD_ORDER between", value1, value2, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andHoldOrderNotBetween(String value1, String value2) {
            addCriterion("HOLD_ORDER not between", value1, value2, "holdOrder");
            return (Criteria) this;
        }

        public Criteria andEventNoIsNull() {
            addCriterion("EVENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andEventNoIsNotNull() {
            addCriterion("EVENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andEventNoEqualTo(String value) {
            addCriterion("EVENT_NO =", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoNotEqualTo(String value) {
            addCriterion("EVENT_NO <>", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoGreaterThan(String value) {
            addCriterion("EVENT_NO >", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_NO >=", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoLessThan(String value) {
            addCriterion("EVENT_NO <", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoLessThanOrEqualTo(String value) {
            addCriterion("EVENT_NO <=", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoLike(String value) {
            addCriterion("EVENT_NO like", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoNotLike(String value) {
            addCriterion("EVENT_NO not like", value, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoIn(List<String> values) {
            addCriterion("EVENT_NO in", values, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoNotIn(List<String> values) {
            addCriterion("EVENT_NO not in", values, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoBetween(String value1, String value2) {
            addCriterion("EVENT_NO between", value1, value2, "eventNo");
            return (Criteria) this;
        }

        public Criteria andEventNoNotBetween(String value1, String value2) {
            addCriterion("EVENT_NO not between", value1, value2, "eventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoIsNull() {
            addCriterion("PROM_EVENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andPromEventNoIsNotNull() {
            addCriterion("PROM_EVENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPromEventNoEqualTo(String value) {
            addCriterion("PROM_EVENT_NO =", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoNotEqualTo(String value) {
            addCriterion("PROM_EVENT_NO <>", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoGreaterThan(String value) {
            addCriterion("PROM_EVENT_NO >", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoGreaterThanOrEqualTo(String value) {
            addCriterion("PROM_EVENT_NO >=", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoLessThan(String value) {
            addCriterion("PROM_EVENT_NO <", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoLessThanOrEqualTo(String value) {
            addCriterion("PROM_EVENT_NO <=", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoLike(String value) {
            addCriterion("PROM_EVENT_NO like", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoNotLike(String value) {
            addCriterion("PROM_EVENT_NO not like", value, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoIn(List<String> values) {
            addCriterion("PROM_EVENT_NO in", values, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoNotIn(List<String> values) {
            addCriterion("PROM_EVENT_NO not in", values, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoBetween(String value1, String value2) {
            addCriterion("PROM_EVENT_NO between", value1, value2, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andPromEventNoNotBetween(String value1, String value2) {
            addCriterion("PROM_EVENT_NO not between", value1, value2, "promEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoIsNull() {
            addCriterion("STAMP_EVENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andStampEventNoIsNotNull() {
            addCriterion("STAMP_EVENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andStampEventNoEqualTo(String value) {
            addCriterion("STAMP_EVENT_NO =", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoNotEqualTo(String value) {
            addCriterion("STAMP_EVENT_NO <>", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoGreaterThan(String value) {
            addCriterion("STAMP_EVENT_NO >", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoGreaterThanOrEqualTo(String value) {
            addCriterion("STAMP_EVENT_NO >=", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoLessThan(String value) {
            addCriterion("STAMP_EVENT_NO <", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoLessThanOrEqualTo(String value) {
            addCriterion("STAMP_EVENT_NO <=", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoLike(String value) {
            addCriterion("STAMP_EVENT_NO like", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoNotLike(String value) {
            addCriterion("STAMP_EVENT_NO not like", value, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoIn(List<String> values) {
            addCriterion("STAMP_EVENT_NO in", values, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoNotIn(List<String> values) {
            addCriterion("STAMP_EVENT_NO not in", values, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoBetween(String value1, String value2) {
            addCriterion("STAMP_EVENT_NO between", value1, value2, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andStampEventNoNotBetween(String value1, String value2) {
            addCriterion("STAMP_EVENT_NO not between", value1, value2, "stampEventNo");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagIsNull() {
            addCriterion("DISPLAY_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagIsNotNull() {
            addCriterion("DISPLAY_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagEqualTo(String value) {
            addCriterion("DISPLAY_FLAG =", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagNotEqualTo(String value) {
            addCriterion("DISPLAY_FLAG <>", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagGreaterThan(String value) {
            addCriterion("DISPLAY_FLAG >", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_FLAG >=", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagLessThan(String value) {
            addCriterion("DISPLAY_FLAG <", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_FLAG <=", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagLike(String value) {
            addCriterion("DISPLAY_FLAG like", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagNotLike(String value) {
            addCriterion("DISPLAY_FLAG not like", value, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagIn(List<String> values) {
            addCriterion("DISPLAY_FLAG in", values, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagNotIn(List<String> values) {
            addCriterion("DISPLAY_FLAG not in", values, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagBetween(String value1, String value2) {
            addCriterion("DISPLAY_FLAG between", value1, value2, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayFlagNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_FLAG not between", value1, value2, "displayFlag");
            return (Criteria) this;
        }

        public Criteria andMdSelectionIsNull() {
            addCriterion("MD_SELECTION is null");
            return (Criteria) this;
        }

        public Criteria andMdSelectionIsNotNull() {
            addCriterion("MD_SELECTION is not null");
            return (Criteria) this;
        }

        public Criteria andMdSelectionEqualTo(String value) {
            addCriterion("MD_SELECTION =", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionNotEqualTo(String value) {
            addCriterion("MD_SELECTION <>", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionGreaterThan(String value) {
            addCriterion("MD_SELECTION >", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionGreaterThanOrEqualTo(String value) {
            addCriterion("MD_SELECTION >=", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionLessThan(String value) {
            addCriterion("MD_SELECTION <", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionLessThanOrEqualTo(String value) {
            addCriterion("MD_SELECTION <=", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionLike(String value) {
            addCriterion("MD_SELECTION like", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionNotLike(String value) {
            addCriterion("MD_SELECTION not like", value, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionIn(List<String> values) {
            addCriterion("MD_SELECTION in", values, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionNotIn(List<String> values) {
            addCriterion("MD_SELECTION not in", values, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionBetween(String value1, String value2) {
            addCriterion("MD_SELECTION between", value1, value2, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andMdSelectionNotBetween(String value1, String value2) {
            addCriterion("MD_SELECTION not between", value1, value2, "mdSelection");
            return (Criteria) this;
        }

        public Criteria andPromotionIsNull() {
            addCriterion("PROMOTION is null");
            return (Criteria) this;
        }

        public Criteria andPromotionIsNotNull() {
            addCriterion("PROMOTION is not null");
            return (Criteria) this;
        }

        public Criteria andPromotionEqualTo(String value) {
            addCriterion("PROMOTION =", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotEqualTo(String value) {
            addCriterion("PROMOTION <>", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionGreaterThan(String value) {
            addCriterion("PROMOTION >", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionGreaterThanOrEqualTo(String value) {
            addCriterion("PROMOTION >=", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLessThan(String value) {
            addCriterion("PROMOTION <", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLessThanOrEqualTo(String value) {
            addCriterion("PROMOTION <=", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionLike(String value) {
            addCriterion("PROMOTION like", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotLike(String value) {
            addCriterion("PROMOTION not like", value, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionIn(List<String> values) {
            addCriterion("PROMOTION in", values, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotIn(List<String> values) {
            addCriterion("PROMOTION not in", values, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionBetween(String value1, String value2) {
            addCriterion("PROMOTION between", value1, value2, "promotion");
            return (Criteria) this;
        }

        public Criteria andPromotionNotBetween(String value1, String value2) {
            addCriterion("PROMOTION not between", value1, value2, "promotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionIsNull() {
            addCriterion("FUTURE_PROMOTION is null");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionIsNotNull() {
            addCriterion("FUTURE_PROMOTION is not null");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionEqualTo(String value) {
            addCriterion("FUTURE_PROMOTION =", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionNotEqualTo(String value) {
            addCriterion("FUTURE_PROMOTION <>", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionGreaterThan(String value) {
            addCriterion("FUTURE_PROMOTION >", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionGreaterThanOrEqualTo(String value) {
            addCriterion("FUTURE_PROMOTION >=", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionLessThan(String value) {
            addCriterion("FUTURE_PROMOTION <", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionLessThanOrEqualTo(String value) {
            addCriterion("FUTURE_PROMOTION <=", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionLike(String value) {
            addCriterion("FUTURE_PROMOTION like", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionNotLike(String value) {
            addCriterion("FUTURE_PROMOTION not like", value, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionIn(List<String> values) {
            addCriterion("FUTURE_PROMOTION in", values, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionNotIn(List<String> values) {
            addCriterion("FUTURE_PROMOTION not in", values, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionBetween(String value1, String value2) {
            addCriterion("FUTURE_PROMOTION between", value1, value2, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andFuturePromotionNotBetween(String value1, String value2) {
            addCriterion("FUTURE_PROMOTION not between", value1, value2, "futurePromotion");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionIsNull() {
            addCriterion("STORE_SELECTION is null");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionIsNotNull() {
            addCriterion("STORE_SELECTION is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionEqualTo(String value) {
            addCriterion("STORE_SELECTION =", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionNotEqualTo(String value) {
            addCriterion("STORE_SELECTION <>", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionGreaterThan(String value) {
            addCriterion("STORE_SELECTION >", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionGreaterThanOrEqualTo(String value) {
            addCriterion("STORE_SELECTION >=", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionLessThan(String value) {
            addCriterion("STORE_SELECTION <", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionLessThanOrEqualTo(String value) {
            addCriterion("STORE_SELECTION <=", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionLike(String value) {
            addCriterion("STORE_SELECTION like", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionNotLike(String value) {
            addCriterion("STORE_SELECTION not like", value, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionIn(List<String> values) {
            addCriterion("STORE_SELECTION in", values, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionNotIn(List<String> values) {
            addCriterion("STORE_SELECTION not in", values, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionBetween(String value1, String value2) {
            addCriterion("STORE_SELECTION between", value1, value2, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andStoreSelectionNotBetween(String value1, String value2) {
            addCriterion("STORE_SELECTION not between", value1, value2, "storeSelection");
            return (Criteria) this;
        }

        public Criteria andPogFlagIsNull() {
            addCriterion("POG_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andPogFlagIsNotNull() {
            addCriterion("POG_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPogFlagEqualTo(String value) {
            addCriterion("POG_FLAG =", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagNotEqualTo(String value) {
            addCriterion("POG_FLAG <>", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagGreaterThan(String value) {
            addCriterion("POG_FLAG >", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagGreaterThanOrEqualTo(String value) {
            addCriterion("POG_FLAG >=", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagLessThan(String value) {
            addCriterion("POG_FLAG <", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagLessThanOrEqualTo(String value) {
            addCriterion("POG_FLAG <=", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagLike(String value) {
            addCriterion("POG_FLAG like", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagNotLike(String value) {
            addCriterion("POG_FLAG not like", value, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagIn(List<String> values) {
            addCriterion("POG_FLAG in", values, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagNotIn(List<String> values) {
            addCriterion("POG_FLAG not in", values, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagBetween(String value1, String value2) {
            addCriterion("POG_FLAG between", value1, value2, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andPogFlagNotBetween(String value1, String value2) {
            addCriterion("POG_FLAG not between", value1, value2, "pogFlag");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(LocalDateTime value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(LocalDateTime value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(LocalDateTime value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(LocalDateTime value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<LocalDateTime> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<LocalDateTime> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andAllowSalesIsNull() {
            addCriterion("ALLOW_SALES is null");
            return (Criteria) this;
        }

        public Criteria andAllowSalesIsNotNull() {
            addCriterion("ALLOW_SALES is not null");
            return (Criteria) this;
        }

        public Criteria andAllowSalesEqualTo(String value) {
            addCriterion("ALLOW_SALES =", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesNotEqualTo(String value) {
            addCriterion("ALLOW_SALES <>", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesGreaterThan(String value) {
            addCriterion("ALLOW_SALES >", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesGreaterThanOrEqualTo(String value) {
            addCriterion("ALLOW_SALES >=", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesLessThan(String value) {
            addCriterion("ALLOW_SALES <", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesLessThanOrEqualTo(String value) {
            addCriterion("ALLOW_SALES <=", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesLike(String value) {
            addCriterion("ALLOW_SALES like", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesNotLike(String value) {
            addCriterion("ALLOW_SALES not like", value, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesIn(List<String> values) {
            addCriterion("ALLOW_SALES in", values, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesNotIn(List<String> values) {
            addCriterion("ALLOW_SALES not in", values, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesBetween(String value1, String value2) {
            addCriterion("ALLOW_SALES between", value1, value2, "allowSales");
            return (Criteria) this;
        }

        public Criteria andAllowSalesNotBetween(String value1, String value2) {
            addCriterion("ALLOW_SALES not between", value1, value2, "allowSales");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TBL_SKU_STORE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}