package com.tgfc.som.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_USER
 */
public class User implements Serializable {
    /**
     * Database Column Remarks:
     *   員工編號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.EMP_ID
     *
     * @mbg.generated
     */
    private String empId;

    /**
     * Database Column Remarks:
     *   通路別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.CHANNEL_ID
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   主店別(NULL表示全通路)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.STORE_ID
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     * Database Column Remarks:
     *   員工姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.EMP_NAME
     *
     * @mbg.generated
     */
    private String empName;

    /**
     * Database Column Remarks:
     *   系統別(逗號分隔系統別)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.SYSTEM_FLAG
     *
     * @mbg.generated
     */
    private String systemFlag;

    /**
     * Database Column Remarks:
     *   停用註記(Y, N)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.DISABLED_FLAG
     *
     * @mbg.generated
     */
    private String disabledFlag;

    /**
     * Database Column Remarks:
     *   權限等級
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.AUTHORITY_GRADE
     *
     * @mbg.generated
     */
    private Short authorityGrade;

    /**
     * Database Column Remarks:
     *   帳號可用時間起
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.START_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime startDate;

    /**
     * Database Column Remarks:
     *   帳號可用時間訖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.END_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime endDate;

    /**
     * Database Column Remarks:
     *   更新日期時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * Database Column Remarks:
     *   更新人員工號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    private String updateEmpId;

    /**
     * Database Column Remarks:
     *   更新人員姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    private String updateEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.EMP_ID
     *
     * @return the value of TBL_USER.EMP_ID
     *
     * @mbg.generated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.EMP_ID
     *
     * @param empId the value for TBL_USER.EMP_ID
     *
     * @mbg.generated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.CHANNEL_ID
     *
     * @return the value of TBL_USER.CHANNEL_ID
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.CHANNEL_ID
     *
     * @param channelId the value for TBL_USER.CHANNEL_ID
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.STORE_ID
     *
     * @return the value of TBL_USER.STORE_ID
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.STORE_ID
     *
     * @param storeId the value for TBL_USER.STORE_ID
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.EMP_NAME
     *
     * @return the value of TBL_USER.EMP_NAME
     *
     * @mbg.generated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.EMP_NAME
     *
     * @param empName the value for TBL_USER.EMP_NAME
     *
     * @mbg.generated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.SYSTEM_FLAG
     *
     * @return the value of TBL_USER.SYSTEM_FLAG
     *
     * @mbg.generated
     */
    public String getSystemFlag() {
        return systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.SYSTEM_FLAG
     *
     * @param systemFlag the value for TBL_USER.SYSTEM_FLAG
     *
     * @mbg.generated
     */
    public void setSystemFlag(String systemFlag) {
        this.systemFlag = systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.DISABLED_FLAG
     *
     * @return the value of TBL_USER.DISABLED_FLAG
     *
     * @mbg.generated
     */
    public String getDisabledFlag() {
        return disabledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.DISABLED_FLAG
     *
     * @param disabledFlag the value for TBL_USER.DISABLED_FLAG
     *
     * @mbg.generated
     */
    public void setDisabledFlag(String disabledFlag) {
        this.disabledFlag = disabledFlag == null ? null : disabledFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.AUTHORITY_GRADE
     *
     * @return the value of TBL_USER.AUTHORITY_GRADE
     *
     * @mbg.generated
     */
    public Short getAuthorityGrade() {
        return authorityGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.AUTHORITY_GRADE
     *
     * @param authorityGrade the value for TBL_USER.AUTHORITY_GRADE
     *
     * @mbg.generated
     */
    public void setAuthorityGrade(Short authorityGrade) {
        this.authorityGrade = authorityGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.START_DATE
     *
     * @return the value of TBL_USER.START_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.START_DATE
     *
     * @param startDate the value for TBL_USER.START_DATE
     *
     * @mbg.generated
     */
    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.END_DATE
     *
     * @return the value of TBL_USER.END_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.END_DATE
     *
     * @param endDate the value for TBL_USER.END_DATE
     *
     * @mbg.generated
     */
    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.UPDATE_DATE
     *
     * @return the value of TBL_USER.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.UPDATE_DATE
     *
     * @param updateDate the value for TBL_USER.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.UPDATE_EMP_ID
     *
     * @return the value of TBL_USER.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public String getUpdateEmpId() {
        return updateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.UPDATE_EMP_ID
     *
     * @param updateEmpId the value for TBL_USER.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public void setUpdateEmpId(String updateEmpId) {
        this.updateEmpId = updateEmpId == null ? null : updateEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER.UPDATE_EMP_NAME
     *
     * @return the value of TBL_USER.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public String getUpdateEmpName() {
        return updateEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER.UPDATE_EMP_NAME
     *
     * @param updateEmpName the value for TBL_USER.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public void setUpdateEmpName(String updateEmpName) {
        this.updateEmpName = updateEmpName == null ? null : updateEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empId=").append(empId);
        sb.append(", channelId=").append(channelId);
        sb.append(", storeId=").append(storeId);
        sb.append(", empName=").append(empName);
        sb.append(", systemFlag=").append(systemFlag);
        sb.append(", disabledFlag=").append(disabledFlag);
        sb.append(", authorityGrade=").append(authorityGrade);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateEmpId=").append(updateEmpId);
        sb.append(", updateEmpName=").append(updateEmpName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getEmpName() == null ? other.getEmpName() == null : this.getEmpName().equals(other.getEmpName()))
            && (this.getSystemFlag() == null ? other.getSystemFlag() == null : this.getSystemFlag().equals(other.getSystemFlag()))
            && (this.getDisabledFlag() == null ? other.getDisabledFlag() == null : this.getDisabledFlag().equals(other.getDisabledFlag()))
            && (this.getAuthorityGrade() == null ? other.getAuthorityGrade() == null : this.getAuthorityGrade().equals(other.getAuthorityGrade()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateEmpId() == null ? other.getUpdateEmpId() == null : this.getUpdateEmpId().equals(other.getUpdateEmpId()))
            && (this.getUpdateEmpName() == null ? other.getUpdateEmpName() == null : this.getUpdateEmpName().equals(other.getUpdateEmpName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getEmpName() == null) ? 0 : getEmpName().hashCode());
        result = prime * result + ((getSystemFlag() == null) ? 0 : getSystemFlag().hashCode());
        result = prime * result + ((getDisabledFlag() == null) ? 0 : getDisabledFlag().hashCode());
        result = prime * result + ((getAuthorityGrade() == null) ? 0 : getAuthorityGrade().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateEmpId() == null) ? 0 : getUpdateEmpId().hashCode());
        result = prime * result + ((getUpdateEmpName() == null) ? 0 : getUpdateEmpName().hashCode());
        return result;
    }
}