package com.tgfc.som.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_USER_STORE
 */
public class UserStore implements Serializable {
    /**
     * Database Column Remarks:
     *   員工編號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.EMP_ID
     *
     * @mbg.generated
     */
    private String empId;

    /**
     * Database Column Remarks:
     *   支援店別代號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.STORE_ID
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     * Database Column Remarks:
     *   通路別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   更新日期時間
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * Database Column Remarks:
     *   更新人員工號
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    private String updateEmpId;

    /**
     * Database Column Remarks:
     *   更新人員姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_USER_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    private String updateEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.EMP_ID
     *
     * @return the value of TBL_USER_STORE.EMP_ID
     *
     * @mbg.generated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.EMP_ID
     *
     * @param empId the value for TBL_USER_STORE.EMP_ID
     *
     * @mbg.generated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.STORE_ID
     *
     * @return the value of TBL_USER_STORE.STORE_ID
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.STORE_ID
     *
     * @param storeId the value for TBL_USER_STORE.STORE_ID
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.CHANNEL_ID
     *
     * @return the value of TBL_USER_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.CHANNEL_ID
     *
     * @param channelId the value for TBL_USER_STORE.CHANNEL_ID
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.UPDATE_DATE
     *
     * @return the value of TBL_USER_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.UPDATE_DATE
     *
     * @param updateDate the value for TBL_USER_STORE.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.UPDATE_EMP_ID
     *
     * @return the value of TBL_USER_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public String getUpdateEmpId() {
        return updateEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.UPDATE_EMP_ID
     *
     * @param updateEmpId the value for TBL_USER_STORE.UPDATE_EMP_ID
     *
     * @mbg.generated
     */
    public void setUpdateEmpId(String updateEmpId) {
        this.updateEmpId = updateEmpId == null ? null : updateEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_USER_STORE.UPDATE_EMP_NAME
     *
     * @return the value of TBL_USER_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public String getUpdateEmpName() {
        return updateEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_USER_STORE.UPDATE_EMP_NAME
     *
     * @param updateEmpName the value for TBL_USER_STORE.UPDATE_EMP_NAME
     *
     * @mbg.generated
     */
    public void setUpdateEmpName(String updateEmpName) {
        this.updateEmpName = updateEmpName == null ? null : updateEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empId=").append(empId);
        sb.append(", storeId=").append(storeId);
        sb.append(", channelId=").append(channelId);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateEmpId=").append(updateEmpId);
        sb.append(", updateEmpName=").append(updateEmpName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserStore other = (UserStore) that;
        return (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getUpdateEmpId() == null ? other.getUpdateEmpId() == null : this.getUpdateEmpId().equals(other.getUpdateEmpId()))
            && (this.getUpdateEmpName() == null ? other.getUpdateEmpName() == null : this.getUpdateEmpName().equals(other.getUpdateEmpName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER_STORE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getUpdateEmpId() == null) ? 0 : getUpdateEmpId().hashCode());
        result = prime * result + ((getUpdateEmpName() == null) ? 0 : getUpdateEmpName().hashCode());
        return result;
    }
}