-- H2 Database Schema (Development)
-- 對齊 Oracle UAT 實際資料表結構
-- 注意：表名和欄位名依據 docs/tables/*.html 定義

-- ================================================================
-- Feature: 001-keycloak-user-login
-- ================================================================

-- TBL_CHANNEL (通路/系統別)
CREATE TABLE IF NOT EXISTS TBL_CHANNEL (
    CHANNEL_ID VARCHAR(10) PRIMARY KEY,
    CHANNEL_NAME VARCHAR(50) NOT NULL,
    POS_CHANNEL VARCHAR(10),
    COMPANY_CODE VARCHAR(10),
    SEQUENCE_NUM INT,
    SAP_CHANNEL VARCHAR(10),
    DC_STORE_ID VARCHAR(10),
    STATUS VARCHAR(1)
);

-- TBL_USER (使用者)
CREATE TABLE IF NOT EXISTS TBL_USER (
    EMP_ID VARCHAR(20) PRIMARY KEY,
    CHANNEL_ID VARCHAR(10),
    STORE_ID VARCHAR(10),
    EMP_NAME VARCHAR(100) NOT NULL,
    SYSTEM_FLAG VARCHAR(50),
    DISABLED_FLAG VARCHAR(1),
    AUTHORITY_GRADE SMALLINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    UPDATE_EMP_ID VARCHAR(20),
    UPDATE_EMP_NAME VARCHAR(100)
);

-- TBL_STORE (店別)
CREATE TABLE IF NOT EXISTS TBL_STORE (
    STORE_ID VARCHAR(10) PRIMARY KEY,
    CHANNEL_ID VARCHAR(10) NOT NULL,
    STORE_NAME VARCHAR(100) NOT NULL,
    SHORT_NAME VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    CLOSE_DATE TIMESTAMP,
    STORE_ADDR VARCHAR(200),
    STORE_TEL VARCHAR(20),
    STATUS VARCHAR(1),
    UPDATE_DATE TIMESTAMP
);

-- TBL_USER_MAST_STORE (使用者主店別)
CREATE TABLE IF NOT EXISTS TBL_USER_MAST_STORE (
    EMP_ID VARCHAR(20) NOT NULL,
    STORE_ID VARCHAR(10),
    CHANNEL_ID VARCHAR(10),
    UPDATE_DATE TIMESTAMP
);

-- TBL_USER_STORE (使用者支援店別)
CREATE TABLE IF NOT EXISTS TBL_USER_STORE (
    EMP_ID VARCHAR(20) NOT NULL,
    STORE_ID VARCHAR(10) NOT NULL,
    CHANNEL_ID VARCHAR(10),
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (EMP_ID, STORE_ID)
);

-- ================================================================
-- Feature: 002-create-order
-- 注意：表名為 TBL_ORDER (非 TBL_ORDER_MAST)
-- ================================================================

-- TBL_ORDER (訂單主檔)
CREATE TABLE IF NOT EXISTS TBL_ORDER (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    PROJECT_ID VARCHAR(20),
    CHANNEL_ID VARCHAR(10),
    STORE_ID VARCHAR(10),
    SYSTEM_FLAG VARCHAR(10),
    ORDER_STATUS_ID VARCHAR(4),
    OUT_STORE_ID VARCHAR(10),
    HANDLE_EMP_ID VARCHAR(20),
    HANDLE_EMP_NAME VARCHAR(100),
    SPECIALIST_EMP_ID VARCHAR(20),
    SPECIALIST_EMP_NAME VARCHAR(100),
    CLOSE_EMP_ID VARCHAR(20),
    CLOSE_EMP_NAME VARCHAR(100),
    CLOSE_DATE TIMESTAMP,
    MEMBER_CARD_ID VARCHAR(30),
    MEMBER_CARD_TYPE VARCHAR(4),
    MEMBER_NAME VARCHAR(100),
    MEMBER_BIRTHDAY DATE,
    MEMBER_GENDER VARCHAR(2),
    MEMBER_CONTACT VARCHAR(100),
    MEMBER_CONTACT_PHONE VARCHAR(20),
    MEMBER_PHONE VARCHAR(20),
    MEMBER_CELL_PHONE VARCHAR(20),
    MEMBER_ADDR_ZIP VARCHAR(10),
    MEMBER_ADDR VARCHAR(200),
    INSTALL_ADDR_ZIP VARCHAR(10),
    INSTALL_ADDR VARCHAR(200),
    ORDER_SOURCE VARCHAR(10),
    INSTALL_CREATED_FLAG VARCHAR(1),
    PO_CREATED_FLAG VARCHAR(1),
    EXPIRED_DATE DATE,
    REMARK VARCHAR(500),
    TRACKING_NO VARCHAR(50),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_EMP_ID VARCHAR(20),
    CREATE_EMP_NAME VARCHAR(100),
    UPDATE_DATE TIMESTAMP,
    UPDATE_EMP_ID VARCHAR(20),
    UPDATE_EMP_NAME VARCHAR(100)
);

-- TBL_ORDER_DETL (訂單明細，PK: ORDER_ID + DETL_SEQ_ID)
CREATE TABLE IF NOT EXISTS TBL_ORDER_DETL (
    ORDER_ID VARCHAR(20) NOT NULL,
    DETL_SEQ_ID VARCHAR(10) NOT NULL,
    STORE_ID VARCHAR(10),
    SKU_NO VARCHAR(20) NOT NULL,
    SKU_NAME VARCHAR(200),
    SUB_DEPT_ID VARCHAR(10),
    CLASS_ID VARCHAR(10),
    SUB_CLASS_ID VARCHAR(10),
    TAX_TYPE VARCHAR(1),
    WORKTYPE_ID VARCHAR(10),
    WORKTYPE_NAME VARCHAR(100),
    DELIVERY_WORKTYPE_ID VARCHAR(10),
    DELIVERY_DATE DATE,
    TRADE_STATUS VARCHAR(1),
    QUANTITY INT DEFAULT 1,
    UNIT_COST DECIMAL(12,2),
    INSTALL_FLAG VARCHAR(1),
    DELIVERY_FLAG VARCHAR(1),
    PARENT_SEQ_ID VARCHAR(10),
    BARCODE VARCHAR(30),
    SKU_STATUS VARCHAR(1),
    HOLD_ORDER VARCHAR(1),
    REMARK VARCHAR(500),
    GOODS_TYPE VARCHAR(10),
    MKT_AMT DECIMAL(12,0),
    REG_AMT DECIMAL(12,0),
    POS_AMT DECIMAL(12,0),
    ACT_POS_AMT DECIMAL(12,0),
    INSTALL_PRICE DECIMAL(12,0),
    DELIVERY_PRICE DECIMAL(12,0),
    ACT_INSTALL_PRICE DECIMAL(12,0),
    ACT_DELIVERY_PRICE DECIMAL(12,0),
    TOTAL_PRICE DECIMAL(12,0),
    DISCOUNT_AMT DECIMAL(12,0),
    DISCOUNT_QTY INT,
    DISCOUNT_TYPE VARCHAR(10),
    DISCOUNT_CODE VARCHAR(20),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (ORDER_ID, DETL_SEQ_ID)
);

-- TBL_ORDER_COMPUTE (訂單試算，PK: ORDER_ID + COMPUTE_TYPE)
CREATE TABLE IF NOT EXISTS TBL_ORDER_COMPUTE (
    ORDER_ID VARCHAR(20) NOT NULL,
    COMPUTE_TYPE VARCHAR(4) NOT NULL,
    STORE_ID VARCHAR(10),
    TOTAL_PRICE DECIMAL(12,0),
    DISCOUNT DECIMAL(12,0),
    ACT_TOTAL_PRICE DECIMAL(12,0),
    ACT_TOTAL_PRICE_TX DECIMAL(12,0),
    ACT_TOTAL_PRICE_NTX DECIMAL(12,0),
    AUTHORIZED_EMP_ID VARCHAR(20),
    AUTHORIZED_EMP_NAME VARCHAR(100),
    AUTHORIZED_REASON VARCHAR(500),
    UPDATE_DATE TIMESTAMP,
    AUTHORIZED_DATE TIMESTAMP,
    PRIMARY KEY (ORDER_ID, COMPUTE_TYPE)
);

-- TBL_SKU (商品主檔)
CREATE TABLE IF NOT EXISTS TBL_SKU (
    SKU_NO VARCHAR(20) PRIMARY KEY,
    SKU_NAME VARCHAR(200),
    BARCODE VARCHAR(30),
    SKU_TYPE VARCHAR(10),
    SUB_DEPT_ID VARCHAR(10),
    CLASS_ID VARCHAR(10),
    SUB_CLASS_ID VARCHAR(10),
    SO_FLAG VARCHAR(1),
    TAX_TYPE VARCHAR(1),
    SKU_STATUS VARCHAR(1),
    OPEN_PRICE VARCHAR(1),
    FREE_DELIVER VARCHAR(1),
    DANGER_FLAG VARCHAR(1),
    DC_TYPE VARCHAR(10),
    HEIGHT DECIMAL(10,2),
    WIDTH DECIMAL(10,2),
    DEEPTH DECIMAL(10,2),
    WEIGHT DECIMAL(10,2),
    MODIFY_TIME TIMESTAMP
);

-- TBL_SKU_STORE (門店商品，PK: SKU_NO + STORE_ID)
CREATE TABLE IF NOT EXISTS TBL_SKU_STORE (
    STORE_ID VARCHAR(10) NOT NULL,
    SKU_NO VARCHAR(20) NOT NULL,
    CHANNEL_ID VARCHAR(10),
    MARKET_PRICE DECIMAL(12,0),
    REGULAR_PRICE DECIMAL(12,0),
    POS_AMT DECIMAL(12,0),
    AVG_COST DECIMAL(12,2),
    SKU_STATUS VARCHAR(1),
    ALLOW_RETURN VARCHAR(1),
    HOLD_ORDER VARCHAR(1),
    ALLOW_SALES VARCHAR(1),
    DISPLAY_FLAG VARCHAR(1),
    MODIFY_TIME TIMESTAMP,
    PRIMARY KEY (SKU_NO, STORE_ID)
);

-- Sequences
CREATE SEQUENCE IF NOT EXISTS SEQ_ORDER_ID START WITH 3000000000 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROJECT_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_ORDER_STORE ON TBL_ORDER(STORE_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDER_MEMBER ON TBL_ORDER(MEMBER_CARD_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDER_STATUS ON TBL_ORDER(ORDER_STATUS_ID);
CREATE INDEX IF NOT EXISTS IDX_DETL_ORDER ON TBL_ORDER_DETL(ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_DETL_SKU ON TBL_ORDER_DETL(SKU_NO);
CREATE INDEX IF NOT EXISTS IDX_SKU_STORE_SKU ON TBL_SKU_STORE(SKU_NO);
CREATE INDEX IF NOT EXISTS IDX_SKU_STORE_STORE ON TBL_SKU_STORE(STORE_ID);
